### PR TITLE
add configuration parameter to skip battery test during initialization

### PR DESCRIPTION
**Pull request by morrishoresh**
I've added the configuration key "driver.flag.nobt". When this flag is set, the battery test during driver initialization will be skipped. I implemented the feature in the powercom driver:

here is a configuration example:
[UPS]
   driver=powercom
   port=/dev/serial/by-id/usb-POWERCOM_CO.__LTD._USB_to_Serial-if00-port0
   type=IMP
   nobt

Apparently, some devices may go into an endless loop of testing the battery even though the battery is ok.

MAINTAINER NOTE: See also issue #546

### CODE REVIEW

**Comment by aquette** [comment]
@morrishoresh a small heads up on this PR: have you seen my above comments?

**Comment by morrishoresh** [comment]
> @morrishoresh a small heads up on this PR: have you seen my above comments?

Yes, I just haven't gotten around to doing this yet.

**Comment by rouben** [comment]
> Hello @morrishoresh 
> 
> 
> 
> some comments:
> 
> * since this parameter is specific to the powercom driver, you should not implement this in main.c, but instead complete powercom.c -> upsdrv_makevartable() and add a call to
> 
> addvar(VAR_FLAG, "nobt", "Disable battery test at init time");
> 
> along with testvar() in upsdrv_initups().
> 
> * you should bump power driver version (from 0.17 to 0.18)
> 
> * document the "nobt" flag in docs/man/powercom.txt -> EXTRA ARGUMENTS
> 
> 
> 
> thanks in advance

@aquette could you please let us know if the list of required changes you quoted above is still valid (no new or modified requirements since 3 years ago)? If so I'd be willing to reissue this PR, as I do have a PowerCom UPS available for testing.

**Comment by rouben** [comment]
I added pull request #1256 to address the changes requested by @aquette. Unfortunately, I don't think I can make the changes here, so I had to make a new PR.

**Comment by rouben** [comment]
This pull request has been superseded by #1256 which has been merged to the master branch. Therefore this pull request can be closed if I am not mistaken.

**Pull request closed without merging**
