### PR TITLE
Added author info for previous merge https://github.com/networkupstools/nut/pull/511

### PR DESCRIPTION
**Pull request by rpvelloso**
@aquette suggested in https://github.com/networkupstools/nut/pull/511 that I added myself as author. No changes were made to source code.

### CODE REVIEW

**Comment by aquette** [comment]
@rpvelloso please pull the latest master to refresh this PR. the initial commit is still listed. thanks

**Comment by rpvelloso** [comment]
@aquette sorry about that. Already pulled latest master.

**Comment by rpvelloso** [comment]
@aquette do you want me to close this and open another one? The commits are still showing...

**Comment by aquette** [comment]
@rpvelloso  something definitely gone wrong.
I'd appreciate if you could remake your author change into a new PR, ensuring that you created your branch from the latest master and that only the author commit is present. Thanks

**Comment by rpvelloso** [comment]
@aquette https://github.com/networkupstools/nut/pull/672

**Pull request closed without merging**
