### PR TITLE
Integrate Eaton/nLogic pdu (snmp)

### PR DESCRIPTION
**Pull request by eric3873**
Integrate nLogic pdu (with snmp driver).
No test done yet with real device (TBC).

### CODE REVIEW

**Review by aquette — APPROVED** [review]

**Review by jimklimov — APPROVED** [review]
Looks good and does not seem to raise any conflicts (e.g. SYSOID is unique) :)
CI got stuck with a network outage between server and agents for a while - pushing the queue through today.

What about the comment of "not yet tested, TBC"? Should the merge be delayed until you signal that the new driver actually works? :)

Also, seeing the many `unmapped` entries here, I've updated the `docs/nut-names.txt` with a note on these - does it look right BTW? :) https://github.com/networkupstools/nut/commit/2b9ca931d4e84e10bbf603a87dd942e45d60c00e

**Comment by aquette** [comment]
Not tested *again* on the real device (originally did few months ago) but tested again with real data using snmpsimd.
Good to merge, thx

**Comment by jimklimov** [comment]
Speaking of which, a docs chapter on use of `snmpsimd` (how to record high-quality response-files that it would answer with, etc.) would be welcome ;)

Is there any such tech for USB or serial - so drivers could be developed or regression-tested against an emulator of an UPS/PDU/...?

**Review by jimklimov — CHANGES_REQUESTED** [review]
Per CI (sorry for unstripped ANSI coloring), something "makes pointer from integer without a cast":

````
In file included from ../../drivers/eaton-pdu-nlogic-mib.h:26
                 from [01m[K../../drivers/eaton-pdu-nlogic-mib.c:25:
[01m[K../../drivers/snmp-ups.h:206:25:[m[K [01;31m[Kerror: [m[Kinitialization of '[01m[Kchar *[m[K' from '[01m[Klong unsigned int[m[K' makes pointer from integer without a cast [[01;31m[K-Werror=int-conversion[m[K]
  206 | #define SU_FLAG_STATIC  [01;31m[K([m[K1UL << 1) /* retrieve info only once. */
      |                         [01;31m[K^[m[K
[01m[K../../drivers/eaton-pdu-nlogic-mib.c:118:3:[m[K [01;36m[Knote: [m[Kin expansion of macro '[01m[KSU_FLAG_STATIC[m[K'
  118 |   [01;36m[KSU_FLAG_STATIC[m[K, SU_FLAG_OK, NULL },
      |   [01;36m[K^~~~~~~~~~~~~~[m[K
[01m[K../../drivers/snmp-ups.h:206:25:[m[K [01;36m[Knote: [m[K(near initialization for '[01m[Keaton_pdu_nlogic_mib[7].dfl[m[K')
  206 | #define SU_FLAG_STATIC  [01;36m[K([m[K1UL << 1) /* retrieve info only once. */
      |                         [01;36m[K^[m[K
[01m[K../../drivers/eaton-pdu-nlogic-mib.c:118:3:[m[K [01;36m[Knote: [m[Kin expansion of macro '[01m[KSU_FLAG_STATIC[m[K'
  118 |   [01;36m[KSU_FLAG_STATIC[m[K, SU_FLAG_OK, NULL },
      |   [01;36m[K^~~~~~~~~~~~~~[m[K
````

**Comment by aquette** [comment]
> @aquette : Speaking of which, a docs chapter on use of `snmpsimd` (how to record high-quality response-files that it would answer with, etc.) would be welcome ;)
> 
> Is there any such tech for USB or serial - so drivers could be developed or regression-tested against an emulator of an UPS/PDU/...?

would be great for snmpsimd indeed. If only I had time :D you may remember why I had to step down from my community roles, no ;)

as for USB/serial sim, nothing that I remember. I even once wanted to create one

**Comment by aquette** [comment]
> @aquette @eric3873 : Per CI (sorry for unstripped ANSI coloring), something "makes pointer from integer without a cast":
> 
> ```
> In file included from ../../drivers/eaton-pdu-nlogic-mib.h:26
>                  from �[01m�[K../../drivers/eaton-pdu-nlogic-mib.c:25:
> �[01m�[K../../drivers/snmp-ups.h:206:25:�[m�[K �[01;31m�[Kerror: �[m�[Kinitialization of '�[01m�[Kchar *�[m�[K' from '�[01m�[Klong unsigned int�[m�[K' makes pointer from integer without a cast [�[01;31m�[K-Werror=int-conversion�[m�[K]
>   206 | #define SU_FLAG_STATIC  �[01;31m�[K(�[m�[K1UL << 1) /* retrieve info only once. */
>       |                         �[01;31m�[K^�[m�[K
> �[01m�[K../../drivers/eaton-pdu-nlogic-mib.c:118:3:�[m�[K �[01;36m�[Knote: �[m�[Kin expansion of macro '�[01m�[KSU_FLAG_STATIC�[m�[K'
>   118 |   �[01;36m�[KSU_FLAG_STATIC�[m�[K, SU_FLAG_OK, NULL },
>       |   �[01;36m�[K^~~~~~~~~~~~~~�[m�[K
> �[01m�[K../../drivers/snmp-ups.h:206:25:�[m�[K �[01;36m�[Knote: �[m�[K(near initialization for '�[01m�[Keaton_pdu_nlogic_mib[7].dfl�[m�[K')
>   206 | #define SU_FLAG_STATIC  �[01;36m�[K(�[m�[K1UL << 1) /* retrieve info only once. */
>       |                         �[01;36m�[K^�[m�[K
> �[01m�[K../../drivers/eaton-pdu-nlogic-mib.c:118:3:�[m�[K �[01;36m�[Knote: �[m�[Kin expansion of macro '�[01m�[KSU_FLAG_STATIC�[m�[K'
>   118 |   �[01;36m�[KSU_FLAG_STATIC�[m�[K, SU_FLAG_OK, NULL },
>       |   �[01;36m�[K^~~~~~~~~~~~~~�[m�[K
> ```

not that readable, but seems in the driver, not in the subdriver

**Comment by jimklimov** [comment]
Off-topic: Just for fun, wondering if these artifacts (when they appear in about 15 minutes) would "just work" for you: https://ci.appveyor.com/project/nut-travis/nut/builds/45387797/artifacts

**Comment by jimklimov** [comment]
`missing field 'oid2info' initializer`

seems we lost a pointer before those flags. Provisorily posting a NULL - maybe an empty string (or hardcoded model?) would be deemed better (feel free to update as fir then)?

**Comment by aquette** [comment]
Thx @jimklimov , I indeed went too fast (and too furious as usual 😅) and missed the dfl field

**Comment by jimklimov** [comment]
Thanks for the contribution!  ;)

**Pull request merged**
