### PR TITLE
DMF code and recipes rearranged to compile cleaner as part of NUT, again

### PR DESCRIPTION
**Pull request by jimklimov**
Major change - LUA code and compiler flags are now compartmentalized, so the project can again be built both with and without LUA capabilities, and successfully builds to the end and regenerates DMF files from scratch without unexpected differences from the Git-saved reference copies. Many temporary or example files from development process are now removed or relocated.

There is still a lot to clean up and revise, but this set of issues was a major roadblock before upstreaming can be discussed :)

(NOTE: This PR duplicates https://github.com/eaton-bob/nut/pull/117 in the original DMF team development repo)

### CODE REVIEW

**Comment by clepple** [comment]
* docs/user-manual.txt.orig should probably be removed
 * whitespace is mostly good (a few spaces versus tabs) except for space at the end of the lines (you can configure `git diff` to show this)
 * constant lists (such as `char *search_paths[]` in common/common.c) should be marked `const`.

Other than that, I can't test much of this (no overlap with the equipment here). Thanks for removing all of the hardcoded `gcc` invocations, etc.

**Comment by clepple** [comment]
There should be a check for `ltdl.h` and the corresponding library functions. Currently, a number of the Buildbot builders (which have all of the previous build-debs for the Debian/Ubuntu NUT packages installed) are failing.

http://buildbot.networkupstools.org/public/nut/builders/Debian-x64-gcc/builds/615/steps/compile/logs/stdio

**Comment by clepple** [comment]
* [ ] There should also be a check for `-std=c11`. http://buildbot.networkupstools.org/public/nut/builders/Ubuntu-precise-x64/builds/550/steps/compile/logs/stdio
 * [ ] Something is not being auto detected correctly on OS X: http://buildbot.networkupstools.org/public/nut/builders/MacOSX-10.11-x64/builds/1324/steps/compile/logs/stdio
 * [ ] Circular DMF dependencies - might be more of a warning, but seem to be present on a few platforms.
 * [ ] Missing dependency? `../../common/common.c:33:25: fatal error: nut_version.h: No such file or directory` ([Ubuntu trusty](http://buildbot.networkupstools.org/public/nut/builders/Ubuntu-trusty-x64/builds/131/steps/compile/logs/stdio))
 * [ ] Many format warnings on Ubuntu wily: http://buildbot.networkupstools.org/public/nut/builders/Ubuntu-wily-x64/builds/133/steps/compile/logs/warnings%20%28149%29

**Comment by clepple** [comment]
* [ ] Correction: still a few hard-coded GCC instances: http://buildbot.networkupstools.org/public/nut/builders/Ubuntu-trusty-x64-clang/builds/134/steps/compile/logs/stdio

**Comment by jimklimov** [comment]
Charles, thanks for the review - I know there's a lot to do still, but
knowing specifics is good (including nits I did not have on the plate) :-)

Regarding whitespace - mostly I cleaned up what my and Carlos's different
IDEs embedded (indentation of tab = 3, 4 or 8 spaces, and empty long-spaces
lines), so code style and indentation is consistent (I did not yet look at
the brace and space-around-parenthesis style though). There should
hopefully have been minimal if any impact on common NUT code that was here
before this chunk of work ;)

Dependency chains were there IIRC due to files that might be (re-)generated
under an alternate builddir but are already there when building in-source.
Mostly this is about the *.dmf files git'ed for reference and regression
tracking (they should not suddenly change - not unless *-mib.c code
changes, or more hacking of DMF generators themselves is done) and
ultimately they are to be installed as part of a package. Another bit of
the problem is using GNU Make syntax, wildcards and functions, which should
be redone for portability. Probably there will be a list of 17 or so
filenames instead of a `*` someplace...

I'm off for today, so will look at code later. And maybe those improvements
will land as another wave of DMF refactoring. But keep the constructive
comments coming ;)

Thanks,
Jim

--
Typos courtesy of GMail on my Samsung Android

16.08.2016 4:39 пользователь "Charles Lepple" <notifications@github.com>
написал:

**Comment by jimklimov** [comment]
Today's changes should fix two major issues:
1) non-portable syntax used in initial makefile (now things that could be wildcarded by GNU make are generated by a helper script)
2) ensuring that we deliver the ietf-mib.dmf symlink with the alphabetically last filename in the stack, because we want anything else to have a chance to match first - IETF is a default fallback.

**Comment by jimklimov** [comment]
Rebased and updated against the recently upstreamed Daisychain branch.

**Comment by jimklimov** [comment]
Hammered the code into passing `make distcheck` again, at least on some platforms.

**Comment by clepple** [comment]
I won't have time to look at the details, but there are still a few `make distcheck` issues on our current Buildbot systems: http://buildbot.networkupstools.org/public/nut/waterfall?branch=pull_305_DMF

(note that our Buildbot configuration only automatically builds branches, so I have to manually sync `pull_305_DMF` with the pull request.)

The "file not found" error on the shell script in OpenBSD might be due to hardcoding `#!/bin/bash` - typically BSD systems have bash optionally installed in `/usr/local/bin`. Might be good to use `#!/usr/bin/env bash`.

Still seeing ltdl-related errors.

Let me know if you want the `Dockerfile`s for the Ubuntu VMs. I don't want to sound like I'm just being difficult by not installing the dependencies yet, but the configuration does resemble the current build environment for Debian/Ubuntu, and I think it's important to make the branch build cleanly either with or without some of the optional libraries.

**Comment by jimklimov** [comment]
@clepple - Don't worry, you're not being difficult... the code and recipes and incompatible tools and platforms are ;)

I agree the resulting work should be portable - so it should either build (and hopefully work), or not stand in the way.

But it seems that for "make distcheck" to try to build everything and pass, that expected set of dependencies for "the everything" should be available (e.g. newly the pycparser to generate the DMFs from C sources and the few progs to test or validate the DMF code and files;, oldly asciidoc or more for the set of documentation, etc.)...

**Comment by clepple** [comment]
My mistake, the buildbot slaves are technically running `make distcheck-light`, which has a few `=auto` settings.

Eventually, I would like to reconfigure this such that only one builder needs all the dependencies installed - then it would build a tarball, and the other builders could fetch that tarball, and wouldn't need to run `make distcheck*`.

**Comment by jimklimov** [comment]
Hopefully recent commits have fixed a number of PR-declared and internally found issues, such as building without LTDL present (now should work either with compile-time dynamic linking or run-time dynamic loading)...

On another note, I think it is helpful to have a pretty diverse build farm with different sets of (un)available packages to check different variants of whatever builds and/or works.

For example, in some buildbot's logs I saw that while dblatex was present, it lacked other tools to actually build PDFs. Perhaps the configure script should not only test presence of tools, but also try to build a page into expected formats and then choose if `auto` becomes a `yes` or `no`...

**Comment by jimklimov** [comment]
@clepple : can you please email me a copy of `/usr/include/x86_64-linux-gnu/sys/sysmacros.h` from `Debian-x64-gcc` host? The error at http://buildbot.networkupstools.org/public/nut/builders/Debian-x64-gcc/builds/623/steps/compile/logs/stdio looks similar to what I fixed earlier in this PR...

Perhaps a test if we want and can use `pycparser` should be done in configure too, otherwise leave existing (in Git/tarball) `*.dmf` files in place. This part is just too fragile, with pycparser barfing on unknown keywords and our sed filter not tossing them all out sometimes on new systems we never saw before ;) ...

**Comment by clepple** [comment]
@jimklimov in case there are other headers needed, that buildslave is running Debian jessie, so you can grab the package from the Downloads section of https://packages.debian.org/jessie/libc6-dev , `ar xv *.deb` (in a temporary directory) and `tar xf data.tar.xz` to get a copy of the installed files. The packages.debian.org site also has a search engine for determining the package that provides a given filename. Similar infrastructure exists at packages.ubuntu.com. I'll kick off another test build shortly.

**Comment by jimklimov** [comment]
I am sort of at loss how another buildbot http://buildbot.networkupstools.org/public/nut/builders/Ubuntu-trusty-x64/builds/139/steps/compile/logs/stdio managed to get into this state:

````
gcc -ggdb -std=c11 -std=gnu99 -Werror -Wall -pedantic -Wc++-compat \
	 -D_FORTIFY_SOURCE=2 -O -fstack-protector \
	 -lltdl   -DWITH_LIBLTDL=1 \
	 -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/.. -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/include -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/../include -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/drivers -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/../drivers -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/tools/nut-scanner -I/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/../tools/nut-scanner  -g -O2 -Wall -Wsign-compare -DWITH_DMF_LUA=0  \
	 -DWITH_DMFMIB=1 -DDMFREINDEXER_MAKECHECK=1 -DDEBUG=1 \
	 -DDEFAULT_DMFSNMP_DIR_OVERRIDE="\"/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/scripts/DMF/dmfsnmp\"" \
	 -o dmf-reindex ../../../tools/nut-scanner/nut-scanner-reindex-dmfsnmp.c ../../../common/dmfsnmp.c ../../../common/common.c ../../../common/str.c
/tmp/ccXdIltx.o: In function `load_neon_lib':
/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/scripts/DMF/../../../common/dmfsnmp.c:193: undefined reference to `lt_dlinit'
/data/buildbot/slave/Ubuntu-trusty-x64/build/nut-v2.7.4-627-g74cb0392.7.4.1/_build/scripts/DMF/../../../common/dmfsnmp.c:209: undefined reference to `lt_dlopen'
````

So apparently it has detected the prereqs for libltdl, at least during the configure phase, and then fails to link with it...

Although true automake recipes look a bit different than what we conjured up for early days of DMF, e.g.

````
gcc -I../../../include -I../../../drivers -I../../../tools/nut-scanner -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNETSNMP_USE_INLINE -Ulinux -Dlinux=linux -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib/perl/5.18/CORE -D_FORTIFY_SOURCE=2 -I/usr/include -I/usr/include/neon -DWITH_DMF_LUA=0 -DDMFREINDEXER_MAKECHECK=0 -g -O2 -Wall -Wsign-compare -o nut-scanner-reindex-dmfsnmp nut_scanner_reindex_dmfsnmp-nut-scanner-reindex-dmfsnmp.o -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now 
````

**Comment by jimklimov** [comment]
Posted a few more probable fixes to recent buildbot-reported errors...

@clepple : If you set the buildbots to fire automatically when the PR is updated, it will become true test-driven development ;)

**Comment by jimklimov** [comment]
Ok, thanks - I'll look at this shortly

--
Typos courtesy of GMail on my Samsung Android

25.08.2016 14:40 пользователь "Charles Lepple" <notifications@github.com>
написал:

**Comment by jimklimov** [comment]
TODO: Pick https://github.com/vyskocilm/nut/commit/1515e43cb93c6ae5373926483df5adc52a2133b9 adding documentation and packaging changes (ietf still should be the last loaded option).

**Comment by jimklimov** [comment]
@clepple : can you please resync the pull-305 branch so buildbot chews on it? So far it last tried a run on a few commits ago, too much ago ;(
Jim

**Comment by clepple** [comment]
Actually, it seems to be a problem with the branch filter. Excluding the most recent libusb-1.0 commit shows the last result from this pull request (7d61db4): http://buildbot.networkupstools.org/public/nut/waterfall?last_time=1472816413

I hadn't seen this because I typically just check http://buildbot.networkupstools.org/public/nut/waterfall

**Comment by jimklimov** [comment]
Do you have a chance to log in to the build host for buildbot.networkupstools.org/public/nut/builders/OpenBSD-x64/builds/458/steps/configure/logs/stdio and check why it finds the current ./autogen.sh but not the `cd ./scripts/DMF ; ./gen-legacy-mibfiles-list.sh`? Is there something more sinister than `make distcheck`'s out-of-tree builds (which I think I did cover by EXTRA_DISTing the script)?..

**Comment by clepple** [comment]
Many BSD systems don't have Bash installed in /bin. "/usr/bin/env bash" would work, I think.

I should probably add some more BSD VMs - the FreeBSD-x86 builder is terribly slow, which is why I haven't tracked down the issues that prompted #311, and the x64 one consumes a lot of power even when idle.

**Comment by jimklimov** [comment]
Ok, i rearranged the offending script to be more plain-shell compatible -
now worked also in dash, ksh and busybox sh. Also changed the test if we
can pycparse C code to produce DMFs to try with the file that causes more
problems (pulls more includes, apparently). So the branch for buildbots can
be resynced :-)

Jim

суббота, 3 сентября 2016 г. пользователь Charles Lepple написал:

**Comment by aquette** [comment]
@clepple , @jimklimov : I just did the manual sync on the pull_305_DMF branch...

**Comment by clepple** [comment]
Not entirely sure why this isn't picking up CFLAGS/CPPFLAGS for net-snmp: http://buildbot.networkupstools.org/public/nut/builders/FreeBSD-x64/builds/415/steps/compile/logs/stdio

**Comment by aquette** [comment]
@jim: there is a ghost in the shell (7 not 42)!
...
snmp-ups.c: In function ‘snmp_ups_walk’:
snmp-ups.c:2284:9: warning: statement with no effect [-Wunused-value]
        }7

@clepple will look for the LIBNETSNMP_* WRT dmf-test, I'm not sure so far but it should be needed...

**Comment by jimklimov** [comment]
Yeah, finally the Buildbot Grid shows a green column! :)

**Comment by clepple** [comment]
as of b67ffe23:
```
../../drivers/snmp-ups.c:92:44: warning: "/*" within comment [-Wcomment]
```

**Comment by jimklimov** [comment]
Thanks @clepple , fixed now. At least it is better than having a `*/` inside a C++ comment ;)

**Comment by jimklimov** [comment]
Note: updated the DMF PR branch with changes from current upstream/master as of 2017-01-08 (saved at https://github.com/jimklimov/nut/tree/DMF-wip-20170107 with original series of commits and occasional merges), and then rebased from current upstream/master (state with same resulting code saved at https://github.com/jimklimov/nut/tree/DMF-wip-20170108).

This had some impact on history of the branch, because many bits developed for it (or referenced/included in it during development) were integrated earlier as standalone PRs and later lived their own life. So as a result of the rebase, some commits got empty and were dropped from history of this branch, and others were rewritten with only a few lines remaining - so not fully implementing the originally documented changes.

Anyhow, the rebased result (unlike the original branch history) applies cleanly on top of current master branch, which helps further integration and testing, and somewhat reduces the amount of differences to review. And as said above, the resulting source code text in the two snapshots at this point is identical.

**Comment by jimklimov** [comment]
Rebased over today's master to take advantage of new Travis CI integration.

At this point, no additional DMF-specific tests are committed (but a few are planned/make sense - e.g. to verify that when `*-mib.c` files change and we regenerate `*.dmf` files, there are no changes to git-tracked versions of the files).

**Comment by jimklimov** [comment]
By agreement with @aquette this PR is finally being merged, so that the common `nut/upstream/DMF` branch at least has code that is not dysfunctional (and is in fact working to its purpose in our variant).

There may be further updates and refinement (e.g. conformance to coding style guideline) to get the DMF branch merged to common `upstream/master` at a later date.

**Pull request merged**
