### PR TITLE
Increase timeout from 250 to 750 ms to allow more time for UPS response

### PR DESCRIPTION
**Pull request by stevegilbert23**
This pull request attempts to resolve issue reported in: https://github.com/networkupstools/nut/issues/542

### CODE REVIEW

**Comment by stevegilbert23** [comment]
I've added an empty commit with sign-off line hoping that will make the difference and get this pull request accepted.

**Comment by 2E0PGS** [comment]
Hi whats the status of this? Is there a branch thats stable I can pull with the merged changes and build manually? I believe the commit @stevegilbert23 wrote is now cherry picked into: https://github.com/networkupstools/nut/tree/libusb-1.0%2B0.1 is this branch stable? when is that branch going to be merged into master?

Is there any other useful changes in that branch which may help fix my problems? I saw quite a bit of talk about the issues with older libusb version here: https://github.com/networkupstools/nut/issues/300

I suspect this is whats causing my problems with powerwalker UPS and `/lib/nut/usbhid-ups -a powerwalker`:

```
May 26 01:56:49 ubuntuserver1 upsd[8689]: Send ping to UPS [powerwalker] failed: Resource temporarily unavailable
May 26 01:56:50 ubuntuserver1 upsd[8689]: Connected to UPS [powerwalker]: usbhid-ups-powerwalker
May 26 01:57:07 ubuntuserver1 upsd[8689]: Data for UPS [powerwalker] is stale - check driver
May 26 02:27:44 ubuntuserver1 upsd[8689]: Send ping to UPS [powerwalker] failed: Resource temporarily unavailable
May 26 02:27:45 ubuntuserver1 upsd[8689]: Connected to UPS [powerwalker]: usbhid-ups-powerwalker
May 26 02:28:02 ubuntuserver1 upsd[8689]: Data for UPS [powerwalker] is stale - check driver
May 26 02:58:43 ubuntuserver1 upsd[8689]: Send ping to UPS [powerwalker] failed: Resource temporarily unavailable
May 26 02:58:45 ubuntuserver1 upsd[8689]: Connected to UPS [powerwalker]: usbhid-ups-powerwalker
May 26 02:59:01 ubuntuserver1 upsd[8689]: Data for UPS [powerwalker] is stale - check driver
May 26 03:29:38 ubuntuserver1 upsd[8689]: Send ping to UPS [powerwalker] failed: Resource temporarily unavailable
```

**Comment by 2E0PGS** [comment]
Whoa my appoligies I noticed you only just cherry picked the commit 20 hours ago or so.

So if it seems sudden to be asking when its going into a release my appologies but hopefull a rough idea if not point me to which branch is best for me to build manually with those changes. Perhaps I will just clone master and modify that line locally myself? But then I maybe missing out on other fixes related to my issue in the libusb branch.

I am running the following system:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
Kernel: x86_64 Linux 4.4.0-96-generic
```

The following libusb versions:
```
sudo apt search libusb | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libusb-0.1-4/xenial,now 2:0.1.12-28 amd64 [installed]
libusb-1.0-0/xenial,now 2:1.0.20-1 amd64 [installed,automatic]
```

**Comment by 2E0PGS** [comment]
It seems others have similair issues which aren't resolved fully: https://github.com/networkupstools/nut/issues/475

**Comment by clepple** [comment]
@2E0PGS the `libusb-1.0+0.1` branch is generally stable (I've been running it for several months with an MGE UPS on FreeBSD), but if the UPS is buggy enough to drop off the USB bus, there may be issues with automatically reconnecting. For Ubuntu, that branch is probably better than `master`, though as you pointed out, you could also cherry-pick this commit onto `master`. Given that you have a PowerWalker UPS, it may be better to post some details of your UPS on issue #475 to see how it compares to the model mentioned there.

Closing this PR since the original 250-to-750-ms commit was cherry-picked onto the intended branch.

**Comment by stevegilbert23** [comment]
@clepple - Appreciate you taking the change.  It doesn't matter to me but I thought I should mention this in case you are not aware.

Some developers now have goals at their jobs like "Contribute to 3 open source projects per year" and typically the metric used is number of pull requests accepted.  In those cases, not accepting a pull request could actually affect someone's compensation.  I've also heard (although this is anecdotal) that in some countries, taking a contribution without attribution may be considered theft.  I have heard this is one reason for requiring the "signed off" lines.

As I said, it does not affect me; I am just sharing.

**Comment by clepple** [comment]
> 
> I've also heard (although this is anecdotal) that in some countries, taking a contribution without attribution may be considered theft. I have heard this is one reason for requiring the "signed off" lines.

I am all for giving credit where credit is due, but the Signed-off-by line doesn't convey much additional information in the absence of something like a Developer's Certificate of Origin. NUT does not have as many layers of reviewers as the projects with DCOs, so the Author line should be sufficient for attribution.

My goal is to keep the main NUT tree from turning into spaghetti. Pull requests with only one or two commits make it harder to separate actual code changes from meta-changes like merges. Commits with no code changes do not help the situation, and probably should be squashed into the previous commit by the original author.

**Comment by 2E0PGS** [comment]
Ok finally running a custom build of branch `libusb-1.0+0.1` after a bit of a cufuffle getting it to build on Ubuntu. See comments: https://github.com/networkupstools/nut/issues/535

Will update on the results.

**Comment by 2E0PGS** [comment]
That's another idea https://forums.freenas.org/index.php?threads/problems-with-eaton-e-series-ups.17192/#post-98018 I could poll the `upsc powerwalker` output and restart the driver if it returns stale. 

I am currently playing with pollfrequency at the moment however I'm sure I tried all that before. Worth a try again.

Something I havn't tried before is adjusting `DEADTIME` and `MAXAGE` which is what I'm testing now.

**Comment by 2E0PGS** [comment]
Ok with adjusting the `pollfrequency` and using a build of the `libusb-1.0+0.1` branch it is dropping out much much less. Only once in 24 hours and that did reconnect succesfully milli seconds later.

**Comment by kaminkehrer** [comment]
Hello,
Tell me how long it need to get this update in the official nut, please.
I using a raspberry as nut server. My OS is raspian strech.
For me the easiest is, to have it available in apt-get.

Another idea is, make the timout as config. Than everybody could use what he/she needs.

Thank in advance
kaminkehrer

**Pull request closed without merging**
