### PR TITLE
Extend battery information collection

### PR DESCRIPTION
**Pull request by aquette**
Add battery.status, battery.capacity.nominal and Li-ion battery cell min/max voltage / temperature

### CODE REVIEW

**Review by clepple — CHANGES_REQUESTED** [review]
This probably needs clarification as to what the min/max represent: observations (reset by an instant command?) or allowed operating voltage/temperature range.

Would also recommend a review by @NUT-RogerPrice.

**Comment by aquette** [comment]
thanks again for your comments @clepple 
On the Eaton unit I used, both min/max temperature and voltage are measurements, so observed values, not settings.
I also don't see a command to reset.

**Comment by NUT-RogerPrice** [comment]
From the point of view of your humble I-D editor, this is the same situation as #1063.  May I suggest handling it as if the I-D was already an RFC, by announcing the proposed addition in mailing list nut-upsuser to get the "rough consensus"   (apparently that means 95% agreement).   Roger

**Comment by aquette** [comment]
small update: these were announced to the mailing list as an RFC for a week, without feedback so far:
https://alioth-lists.debian.net/pipermail/nut-upsuser/2021-August/012485.html

Is a "no answer / objection" considered as a rough consensus? If so, is there some time limit / deadline attached, to consider the merge of such proposal?

**Pull request merged**
