### PR TITLE
Add support for Delta UPS Amplon R Series

### PR DESCRIPTION
**Pull request by jungeonkim**
This PR adds support for Delta UPS Amplon R Serise (https://www.deltapowersolutions.com/en/mcis/1kva-3kva-single-phase-ups-r-series.php)
Tested on R1K and R3K model. 

```
battery.capacity: 100
battery.charge: 100.0
battery.charge.low: 20
battery.charge.warning: 20
battery.runtime: 6496
battery.temperature: 31.9
battery.voltage: 54.1
battery.voltage.nominal: 48
device.mfr: DELTA
device.model: UPS202R2000B0BA
device.serial: [reduced]
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 5
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4-1-gb34f2434
driver.version.data: Delta UPS HID 0.1
driver.version.internal: 0.41
input.frequency: 59.9
input.sensitivity: normal
input.source: normal
input.transfer.high: 280
input.transfer.high.max: 280
input.transfer.high.min: 270
input.transfer.low: 80
input.transfer.low.max: 90
input.transfer.low.min: 80
input.voltage: 218.0
output.current: 0.0
output.frequency: 59.9
output.frequency.nominal: 60
output.voltage: 218.0
output.voltage.nominal: 220
ups.beeper.status: enabled
ups.delay.start: 0
ups.load: 8.0
ups.mfr: DELTA
ups.model: UPS202R2000B0BA
ups.power.nominal: 2000
ups.productid: 041b
ups.realpower: 155.0
ups.serial [reduced]
ups.start.auto: yes
ups.status: OL
ups.timer.reboot: 0
ups.timer.shutdown: -1
ups.timer.start: 0
ups.type: online
ups.vendorid: 05dd
```

### CODE REVIEW

**Comment by jimklimov** [comment]
Looks quite solid to me, thanks!

Before merging, I'd rather wait a few days for comments from other community members though.

**Review by jimklimov — APPROVED** [review]
Is this a corporate or volunteer contribution? In the former case, you may want to add an entry to docs/acknowledgements.txt

**Comment by jungeonkim** [comment]
> Is this a corporate or volunteer contribution? In the former case, you may want to add an entry to docs/acknowledgements.txt

This is volunteer contribution.

**Review by aquette — APPROVED** [review]
Lgtm
Still, you will want to list it in the manpage, driver.list and to provide a data dump for the DDL. Thanks for your contribution

**Comment by jungeonkim** [comment]
@aquette How can I provide a data dump?

**Comment by jimklimov** [comment]
Thanks for the PR and sorry about the delay for your question. The NUT DDL is documented and displayed at https://networkupstools.org/ddl/index.html for example; typically is is a report of `upsc ups@localhost` to save a snapshot of what fields are recognized by this driver (version) for this device, and sample reasonable values for them.

**Comment by jimklimov** [comment]
Note to self: on the line above the Vendor ID macro there should be a comment with vendor name, it is used by the script which generates udev rules. Like in commit 01efa50 fixed now :)

**Pull request merged**
