### PR TITLE
Update libusb-1.0 branch from upstream/master

### PR DESCRIPTION
**Pull request by jimklimov**
Bring the codebases up to date, and sanitize code style a little bit.

One of competing solutions for issue #300.

### CODE REVIEW

**Comment by jimklimov** [comment]
Bumped the code from current master, and added a fix for #477

**Comment by jimklimov** [comment]
Review question: The error report about whatever reason of device in-accessibility was now bumped from level 2 to level 0 - so it would be visible when a driver fails to connect (subject to `libusb` doing its job well - with 0.1 apparently lacking in this regard, and 1.0 doing this better). Is usage of level 0 acceptable here?

**Comment by clepple** [comment]
@jimklimov Is this merge urgent? IMHO. we really need to figure out what was going on with the double commits in the `libusb-1.0` branch first (see discussion at #300). I was planning on taking a look this weekend, but other things came up. Hopefully, we can re-branch and roll back `libusb-1.0` to before the merge of the doubled commits, and cherry pick any other necessary commits.

**Comment by jimklimov** [comment]
Nothing urgent beside review in progress for #477 - so maybe by cleanup/cherrypick time this code should be merged. Note one of the commits is style fix for codebase here.

**Comment by jimklimov** [comment]
Resynced my PR-origin branch from current NUT master branch

**Comment by jimklimov** [comment]
@clepple @zykh : per https://travis-ci.org/github/networkupstools/nut/jobs/734280072 there are issues between master's (?) nutdrv_qx.c and libusb-1.0 branch codebase; I did not dig deeper but guess it could be because of API changes?..

**Pull request merged**
