### PR TITLE
gitlog2changelog: Date header only occurs at start of line

### PR DESCRIPTION
**Pull request by clepple**
Alternative to https://github.com/networkupstools/nut/pull/427

### CODE REVIEW

**Comment by clepple** [comment]
@jimklimov this version only considers dates in the commit metadata, rather than in the body of the commit. Otherwise, some of the larger commits get the dates stripped out of the constituent patches.

**Comment by jimklimov** [comment]
I'm not sure about the expected correct input format, so perhaps your solution is better. Still, maybe there is value in merging both - mine as a fallback (to log a problem and not abort).

**Comment by clepple** [comment]
Agreed, since with the original code, an exception would get logged, but the build would continue.

We are no longer looking for `Date:` headers inside the body of the commit message, so the chance of that try/except block being used is slim (would mean that the `git log` format had changed). But it's there for completeness, along with a new check for the `Author:` header.

**Comment by jimklimov** [comment]
Ok, thanks, LGTM now :)

Did you test this on potentially offending commits (e.g. with patch-email "Date:" indented headers in the commit comment, as seen in `git log`... possibly some are now in the master branch's log)?

**Comment by clepple** [comment]
I've been meaning to look for other examples not on master, but then again, I am pretty sure that only `git log` metadata will match the `startswith('Date:')` - commit messages will be indented.

**Pull request merged**
