### PR TITLE
EATON HID: add missing usages and paths (initial)

### PR DESCRIPTION
**Pull request by arnaudquette-eaton**
Preliminary complement on Eaton HID usages and paths.
This will require additional work (lookup functions) and tests

Ref: #2495

### CODE REVIEW

**Comment by masterwishx** [comment]
i made some changes but have permissions error on push here , how the best way to add changes here or on my github with what commands?

**Comment by masterwishx** [comment]
https://github.com/networkupstools/nut/pull/2637 added here

**Comment by jimklimov** [comment]
@masterwishx : I think it would be logistically easiest if we just make a new PR (targeted to NUT `master` branch) from your repo/branch e.g. https://github.com/masterwishx/nut/tree/work/2495 source of that "PR into PR", so it would include Arnaud's commits as foundation and results of your practical experimentation and enhancement on top of that, with the branch being yours to edit as any other PR.

@arnaudquette-eaton : just in case, do you know if Eaton Ellipse ECO 650 firmware/hardware can manage its outlets? It declares two, and currently NUT can only read that they exist but offers nothing further about them. Is there anything to strive for (more vendor commands to find and implement), or it just can not turn them on/off independently?

**Comment by arnaudquette-eaton** [comment]
@jimklimov already spawned into #2637, with comments from me ;)
and obviously no, I don't follow anymore the HW for a decade, and USB HW for almost 2 decades

**Comment by jimklimov** [comment]
Superseded by PR #2639

**Pull request closed without merging**
