### PR TITLE
Add 'nowait' option for upsdrvctl in ups.conf

### PR DESCRIPTION
**Pull request by jimklimov**
Upstreaming fixes applied to our project at work

From: Arnaud Quette <arnaud.quette@free.fr>
Date: Sat, 7 Jun 2014 02:27:15 +0200
Subject: [PATCH] Add 'nowait' option for upsdrvctl in ups.conf

The nowait flag allow to tell upsdrvctl to not wait at all for the
driver(s) to execute the request command. The default behavior, when
this variable is omitted, is to wait 'maxstartdelay' seconds

### CODE REVIEW

**Comment by aquette** [comment]
@clepple , @zykh , @balooloo : any objection to merge this one.
I've made it once to be able to start 2000 nut drivers, without waiting for an eternity...

**Comment by jimklimov** [comment]
Pinging @clepple , @zykh : Any objections to merging this feature? Last call at the bar! ;)

**Comment by clepple** [comment]
haven't had time to try it, but as long as the new behavior isn't the default, I don't have any objections.

**Comment by jimklimov** [comment]
Per Arno's documentation, the flag is *optional* and "The default (omission) is to wait."

**Comment by zykh** [comment]
No objection.

**Pull request merged**
