### PR TITLE
Huawei UPS2000: Update Man Page, Change Logic for "load.on" command

### PR DESCRIPTION
**Pull request by biergaizi**
This commit introduces three minor changes after #954 merge.

* Thanks to the user report by @whc2001 in #1066, we finally have a beta tester with a UPS2000-G model with positive result. This commit adds UPS2000-G-3KRTS to the list of tested model in the man page, with slightly updated instructions for submitting new user reports. Two minor typos in the man page are also fixed.
* Currently the driver prevents the user from executing `load.on` when the UPS is already on, and reports a `STAT_INSTCMD_FAILED` with error logs. While executing "load.on" when the UPS is already in "normal-mode on" has no effect, it's still a legal command and should not be rejected arbitrarily, which can potentially confuse downstream applications and users (Update: But we still need to do this if the UPS is in bypass mode, because the UPS would otherwise enter normal mode - "load.on" is not supposed to do that).
* The previous driver also contains two misleading typos in the error logs: (1) it incorrectly suggests `bypass.off` instead of `bypass.stop`, and (2) reports `failed: reason unknown.` when the reason is simply an already-on UPS.

    This commit allows `load.on` to execute when it's already on, and changes the log messages from errors to warnings. Typos in the log messages are also fixed.

### CODE REVIEW

**Comment by jimklimov** [comment]
For the sake of code evolution, I'd explicitly check if the status is "on" and not assume that not-off not-bypass means "on". And then the remaining reason could be an error and an unknown.

**Review by jimklimov — APPROVED** [review]
Looks good, with one suggestion to make it more robust.

**Comment by jimklimov** [comment]
Since my comments above can be addressed "immediately" or later, I'll shelf this PR for a day or two and merge (if there is no feedback before that, to change the plan)

**Comment by biergaizi** [comment]
> I'd explicitly check if the status is "on" and not assume that not-off not-bypass means "on". And then the remaining reason could be (or not be) an error case and an unknown situation.

According to NUT's coding standard on status flags ([docs/new-drivers.txt, line 218](https://github.com/networkupstools/nut/blob/master/docs/new-drivers.txt#L218)), the allowed status flags are, `OL`, `OL`, `LB`, `HB`, `RB`, `CHAG`, `DISCHRG`, `BYPASS`, `CAL`, `OFF`, `OVER`, `TRIM`, `BOOST`, or `FSD`, and their combinations.this is exactly what my driver does. The lookup table for setting the power status is defined in [`ups2000_status_reg[]`, line 676](https://github.com/networkupstools/nut/blob/fa86fc87da478aa0b84a3e719b7b22853d3c4fc0/drivers/huawei-ups2000.c#L676)

Since there is no single `ON` flag to check, I originally coded it to check the absence of the `OFF` flag. Here, I read your suggestion as adding three separate string tests for `OL`, `OB`, and `BYPASS`. Is it what you meant?

> And then the remaining reason could be (or not be) an error case and an unknown situation. 

The lack of an `OFF` flag conclusively decides that the UPS is on. When the UPS status is updated, the code must set either `OL`, `OB`, `OL ECO`, `BYPASS`, or `OFF`. 


Otherwise the code logs an error and report a data stale immediately. 


I have no strong opinion on whether the driver should try to proceed issuing "load.on" to the device - if really the worst case is "no effect", then go for it :)

I looked around and am not convinced at the moment whether dstate ups.status is always a single string token, or if it can have several flags listed (OL CHRG and so on), so decided to not barge into your PR code with an unilateral fix :)


Likewise, please check (maybe later with another PR if needed) if the UPS can have such a composite status for "OFF" and "BYPASS" cases.

**Comment by biergaizi** [comment]
> I'd explicitly check if the status is "on" and not assume that not-off not-bypass means "on". And then the remaining reason could be (or not be) an error case and an unknown situation.

According to NUT's coding standard on status flags ([docs/new-drivers.txt, line 218](https://github.com/networkupstools/nut/blob/master/docs/new-drivers.txt#L218)), the allowed status flags are, `OL`, `OB`, `LB`, `HB`, `RB`, `CHAG`, `DISCHRG`, `BYPASS`, `CAL`, `OFF`, `OVER`, `TRIM`, `BOOST`, or `FSD`, and their combinations. 

This is exactly what my driver does. I originally coded it to check for the absence of the `OFF` flag, because there is no one single `ON` flag to check. Here, I read your suggestion as adding three separate string tests for `OL`, `OB`, and `BYPASS`. Does it sound reasonable to you? If so, I'll push a new revision to include this change.

> And then the remaining reason could be (or not be) an error case and an unknown situation. 

In the original code, the lack of an `OFF` flag conclusively decides that the UPS is on. When the UPS status is updated, the code must set either  `OL`, `OB`, `OL ECO`, `BYPASS`, or `OFF`, because it is one of the five possible mutually exclusive values returned by the "power supply mode" register (*Table 2-1 Collection signal list*, number 1024, datasheet page 32)

> 0: no power supplied
> 1: bypass mode
> 2: mains mode
> 3: battery mode
> 5: mains ECO

If the value in the register is invalid, it triggers both `dstate_datastale();` and `STAT_INSTCMD_FAILED` with a fatal error logged. Therefore, the logic to check the lack of the `OFF` flag is conclusive and complete. 

On the other hand, I do agree that an extra `else` for an unreachable condition is still a good programming practice, and checking for the positives instead of the negatives makes the code more readable.

> I have no strong opinion on whether the driver should try to proceed issuing "load.on" to the device - if really the worst case is "no effect", then go for it :)

Thanks for the reminder. As I was writing this, I do realize that the UPS has 5 possible states. I'll do an exhaustive test to ensure it's really the case in all conditions. 

> I looked around and am not convinced at the moment whether dstate ups.status is always a single string token, or if it can have several flags listed (OL CHRG and so on), so decided to not barge into your PR code with an unilateral fix :)

Register handling in this driver is declarative and data-driven. Let me elaborate on the logic of the code and how the status flags are currently set in the driver. 

First, the lookup table for setting the dstate (both `ups.status`, and `battery.charger.status`) is defined in [`ups2000_status_reg[]`, line 676](https://github.com/networkupstools/nut/blob/fa86fc87da478aa0b84a3e719b7b22853d3c4fc0/drivers/huawei-ups2000.c#L676).

 	{ 1024, 1 /* bool must_set_flag */ , {
            /* status,  val, bit */
		{ "OFF",      0, -1, NULL, NULL },
		{ "BYPASS",   1, -1, NULL, NULL },
		{ "OL",       2, -1, NULL, NULL },
		{ "OB",       3, -1, NULL, NULL },
		{ "OL ECO",   5, -1, NULL, NULL },
		{ NULL,      -1, -1, NULL, NULL },
	}},
    /* definition for additional registers follows */

Function `ups2000_update_status()` loops over the register definitions in `ups2000_status_reg[]` one by one, reads a register and set the corresponding flags via `status_set()` or `dstate_setinfo()` accordingly. The first entry, register 1024, set either the `OFF`, `BYPASS`, `OL`, `OB`, or `OL ECO` flag according to the value of the register, which can be `0`, `1`, `2`, `3` or `5`.

There's a risk that the register may contain an invalid value and set none of the status, to prevent this, there's Boolean condition `must_set_flag` in the register definition. When `ups2000_update_status()` loops over this register but does not set any flag, the function returns failure code `1` to the caller.

After the first register 1024 is processed, more UPS status flags governed by additional registers are subsequently append to the status flag in the next loop iteration over the lookup table. 

> Likewise, please check (maybe later with another PR if needed) if the UPS can have such a composite status for "OFF" and "BYPASS" cases.

While other combinations, like `OL CHRG` are possible, a combination of different power conditions, like `OFF` and `BYPASS` is not, because the register can only take 1 out of 5 mutually exclusive values.

**Comment by jimklimov** [comment]
Ok, great thanks for the clarifications and additional pass over this :)

Then, what would you currently propose: should I merge this PR "as is", or do you plan some further tests/development (the "else" case?) to be sure, in the coming few days?

**Comment by biergaizi** [comment]
Please don't merge it for now. I'll revise the patch & do a force-push later. Thanks.

**Comment by biergaizi** [comment]
Patch has been updated. 

Here's the relevant portion of the commit message: The logic for the off test is reworked to improve readability. The original code checks whether the UPS is on by testing the negative "not OFF" condition, which is not easy to understand - the reader must have intimate knowledge on the code to know its correctness. Namely, When the UPS power status is updated, 1 of the 5 mutually exclusive flags, OL, OB, OL ECO, BYPASS, or OFF is always set, thus the absence of the OFF flag always reliably indicates an ON status. This commits converts the single negative "not OFF" test to three positive tests for "OL", "OB" and "OFF", with additional comments added on reachable and unreachable conditions. Thus, previous uncertainty is eliminated.

**Review by jimklimov — APPROVED** [review]
Thanks a lot! Do you consider this improvement completed, can it be merged? :)

**Comment by biergaizi** [comment]
This patch needs some additional work. I retested it and found the UPS actually automatically enters normal mode upon receiving the "load.on" command in bypass mode. Possibly, this was my original and forgotten motivation for rejecting this command. Oops.

This is an edge case and I'm not sure what's the best way to handle this. Should we reject this command or accept this behavior?

1. If we define "load.on" as "ask the UPS to deliver power to the load", we should accept it. But it seems to make `bypass.stop` redundant, and it's not something we want.

2. If we define "load.on" as providing power to the load, regardless of its source...
    * When the UPS is in bypass mode, we should reject this command.
    * However, this has additional implications - when the UPS is in bypass mode but external power is not available, it should enter normal mode.

3. If we define "load.on" strictly as a normal mode power switch, we should reject it whenever the UPS is in bypass mode.

After some thoughts, I think Option 3 is the preferred option. It'll be a one-line change to add an extra `return STAT_INSTCMD_FAILED;`. Also, I think NUT needs to standardize this behavior in the documentation. Other drivers may have the same problem.

**Comment by biergaizi** [comment]
This problem also needs additional clarifications on other UPS systems if they have separate output power controls. For example, if a hypothetical UPS has `load.on` and `load.off` that only control the output power relay without any association to its current power status, online or bypass, then it would be a non-issue. Defining "`load.on` strictly as a normal mode power switch" would be a bad definition.

A more appropriately definition can be: load.on: Turn on the load immediately, without entering or exiting from bypass mode.

**Comment by jimklimov** [comment]
Thanks, those are very good questions. I've CC'ed some experienced team members whose review about the architecture of NUT and goals of some toggles may be more relevant, so I'd learn something too :)

**Comment by jimklimov** [comment]
Offline comment from @aquette : "between 2 and 3, with a preference for 3"

**Comment by biergaizi** [comment]
I updated the commit. Now it rejects `load.on` in bypass mode. This change has been tested on my system.

**Review by jimklimov — APPROVED** [review]

**Comment by whc2001** [comment]
Just tried almost everything on my device, seems like everything is working!

- `upsc` Display Info
  
  - [x] Info
  
  - [x] Stale & Recover from Stale

- Flags Test
  
  - [x] OL
  
  - [x] OB
  
  - [ ] ECO (To test later, need to consult the user manual for enabling it)
  
  - [x] BYPASS
  
  - [x] OFF
  
  - [x] CAL
  
  - [x] DISCHRG

- Buzzer
  
  - [x] On
  
  - [x] Off
  
  - [x] Toggle

- Bypass
  
  - [x] Start
    
    - [x] Shall ignore `load.on` when in bypass
      - In `2.7.4-3515-gad84d9d2`, `upscmd` still returns `OK` when executing `load.on` during `BYPASS`, but in syslog there actually is `load.on error: UPS is already on, and is in bypass mode. To enter normal mode, use bypass.stop`.
  
  - [x] Stop

- Load
  
  - [x] On
  
  - [x] Off

- Test
  
  - [x] Quick
  
  - [x] Deep
  
  - [x] Stop

- Shutdown
  
  - [x] Stay Off
  
  - [x] Return
  
  - [x] Reboot
  
  - [x] Graceful Reboot

- Parameters
  
  - [x] OnDelay=60
  
  - [x] OnDelay=180
  
  - [x] OffDelay=RebootDelay=6
  
  - [x] OffDelay=RebootDelay=30
  
  - [x] RebootDelay=60

**Comment by jimklimov** [comment]
Possibly the question of #1391 is relevant in this driver too, seeing the comment above for https://github.com/networkupstools/nut/blob/fa86fc87da478aa0b84a3e719b7b22853d3c4fc0/drivers/huawei-ups2000.c#L676

**Pull request merged**
