### PR TITLE
support for PowerWalker VFI 2000 TGS by usbhid-ups

### PR DESCRIPTION
**Pull request by Links2004**
see #560

### CODE REVIEW

**Comment by clepple** [comment]
Please squash these two commits together.

**Comment by Links2004** [comment]
done

**Comment by aquette** [comment]
trying to resurrect this PR:
* there is indeed an issue between liebert-hid.c and mge-hid.c, which both defines 0x06da / 0xffff due to the OEM behind (Phoenixtec)
* I need to test your present modification, but at first sight, there is some conflict between few vars.
* if the above issue is proven, I'd be in favor of putting the adapted content from mge-hid with your mods into liebert-hid.c

**Comment by jimklimov** [comment]
Looking quickly into the vendorID clash, it seems that "Liebert/Phoenixtec HID" is tracked since at least 2012, and the same VID was added to mge-hid.c with commit a08a2292af in 2016 (perhaps after NUT 2.7.4 release, did not check dates closer), apparently because AEG PROTECT NAS began using that instead of an earlier VID recorded in the file.

I do not know if really those "newer" AEG devices use the MGE protocol as the "older" ones did, or also switched to a Liebert dialect along with the chip. Maybe the subdriver should check that this vendor id is accompanied by string containing "AEG" to keep processing with mge-hid and otherwise mark as unsupported so liebert-hid would take over? Or just drop that ID from mge-hid?

Maybe an extended subdriver matcher (or structure at least) like that used in `nutdrv_qx.c` to consult more fields than the basic two is a better solution for other drivers as well.

Either way, it does not seem that PowerWalker devices are particularly "married" to one or another HID Vendor, and Liebert HID was there first :)

**Comment by jimklimov** [comment]
Transplanted the lines from mge-hid.c to liebert-hid.c so as to not break the former.

It seems that the mapping table for mge-hid has many more entries than liebert-hid. I have no idea if those other mapped entries are actually served by Liebert/Phoenixtec devices or come from other vendor subdrivers using that file. Original issue #560 has a data walk from this UPS which can help select the missing mappings for served data points (copy-paste from mge-hid?) but this is something better done with (and tested against) a real device.

**Comment by jimklimov** [comment]
Looking at the usbhid-ups.c driver source, it seems that it goes through the subdrivers array and calls their `claim()` methods until someone says the device is handled. This way the mge subdriver probably grabs 0x06da and liebert subdriver never gets a chance. Posted PR #1357 to try addressing that gap.

**Pull request merged**
