### PR TITLE
nutdrv_qx.c: add support for Armac UPS (or maybe other richcomm) from #1247

### LINKED ISSUE #1238: I'd like to add support for Armac UPS
Hello,
  I have http://armac.pl/oferta/ups-rack-line-interactive-r2000ipsw/ and should be able to add support for it, but I wonder how to do it best and if there's some place to talk/consult the approach. I've sniffed and reveng a bit it's "native" 2005-old, x86, hideous driver. 

Bus 002 Device 008: ID 0925:1234 Lakeview Research UPS USB MON V1.4

It has USB port with "emulated serial" over control + interrupt transfers. It generally supports Q1-like protocol (I found Q1\r, I, F, Q for alarm, T01 for test commands).  Its driver seems to support the richcomm protocol but it doesn't seem to be used with this model, and richcomm_usb doesn't work with it either (connects, but decodes the status badly).

Commands are 4 byte long, whereas answers are *6* byte long. As far as I understand both Blazer and nutdrv_qx drivers use 8 byte long transfers which is(?) the main problem.

What should I do? Copy some matching subdriver of nutdrv_qx and try to code it there? Use blazer? Or maybe I'm missing something obvious?

Cheers,

### PR DESCRIPTION
**Pull request by jimklimov**
After my git-pushing accident (fat-fingered maintainer is sorry), this PR follows up from #1247 including some fixes over it.

> Based on Armac R/2000I/PSW, but should support other UPSes that work with "PowerManagerII" software from Richcomm Technologies from around 2004-2005.
> Closes #1238
> Tested to support querying, short and 10 minute tests. UPS is currently 300km from me so I can't pull the plug to test status change though. I'm unsure about battery measurement - seems to return different values than richcomm software. Otherwise seems to work.

### CODE REVIEW

**Comment by blaa** [comment]
Thanks for the fixes! You could've push me to do some of those certainly. 

I'm back home and testing currentlty the discharge cycle. So far, so good:
```
20211228 205708 100 241.0 11 [OL] 33.0 50.0
20211228 205738 100 240.0 10 [OL] 33.0 50.0
20211228 205808 100 0.0 10 [OB] 33.0 0.0
20211228 205838 100 0.0 10 [OB] 32.0 0.0
```

So far, the battery level is consistent with what the UPS shows on LCD.

**Comment by blaa** [comment]
Low Battery status works as well:
```
20211228 221738 38 0.0 11 [OB LB] 50.0 0.0
20211228 221808 35 0.0 10 [OB LB] 48.0 0.0
```
NUT says 35%, UPS starts to blink the 25% indicator (it has 25, 50, 75 and 100).

I can try the code from this branch too.

**Comment by blaa** [comment]
Just fetched this branch, build and tested - works fine!

**Comment by jimklimov** [comment]
CI says (and review confirms) this PR needs some more changes to adjust to the upstream-master codebase evolution, in particular due to the libusb-1.0 support merge, the `usb_strerror` is no longer correct but `nut_usb_strerror` should cover it for both API versions. Also there seems to be a bit of mess with whitespaces.

**Comment by blaa** [comment]
I can't really work on your branch I guess, but I can do some patches if you like. This usb_strerror doesn't look complicated. And I can fix the whitespace if I just understand how nut wants it. ;) Probably alter changed lines to match rest of file (which as far as I remember was a bit of a mess before, maybe no longer)

**Comment by jimklimov** [comment]
Right, sorry about that - several PRs had similar issue pattern, so I pasted before I realized this one comes from my branch :\ 
Thanks for reminding, hopefully rectified now.

**Comment by blaa** [comment]
Thanks. I could have made some changes, just wanted to figure out a workflow.  I just pulled the branch, made clean, autogen, configure, make and retested using true hardware - still goes "brrrrrr" as it should. Libusb included in upsc output:

```
project ~ # upsc armac
Init SSL without certificate database
battery.charge: 100
battery.voltage: 54.00
battery.voltage.high: 52.00
battery.voltage.low: 41.60
battery.voltage.nominal: 48.0
device.type: ups
driver.name: nutdrv_qx
driver.parameter.nominal_cell_voltage: 13
driver.parameter.number_of_battery_cells: 4
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.productid: 1234
driver.parameter.subdriver: armac
driver.parameter.synchronous: no
driver.parameter.vendorid: 0925
driver.version: 2.7.4-4399-g16687eb71
driver.version.data: Megatec 0.06
driver.version.internal: 0.31
driver.version.usb: libusb-0.1 (or compat)
input.current.nominal: 14.0
input.frequency: 50.0
input.frequency.nominal: 50
input.voltage: 239.0
input.voltage.fault: 140.0
input.voltage.nominal: 220
output.voltage: 237.0
ups.beeper.status: disabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: Ver1.00
ups.load: 11
ups.productid: 1234
ups.status: OL
ups.temperature: 32.0
ups.type: offline / line interactive
ups.vendorid: 0925

```

**Comment by convicte** [comment]
Hi @blaa @jimklimov,

I've been in touch with Armac directly, to seek additional information about NUK compatibility, and their documentation.
Their devices seem quite nice and competitively priced, so I am interested in buying a couple.

Their sales rep was kind enough to contact the team and provide this NUK reference information as their 'communication protocol:

```
Network UPS Tools: Megatec Protocol information
                        VERSION : 2.7

                        DATE : SEP. 30, 1995

		DATE	:V2.7	: JULY 30 ,1996

DATE	DESCRIPTION	MODIFY BY	
2.6	95-9-30	UPDATE "D" COMMAND (SS.SS -> SSS.SS)	Kevin Chiou	
2.7	96-8-01	Disable "D" COMMAND	Kevin Chiou	
				
A. General: This document specifies the RS232C communication protocol of
            the Advance-Intelligent UPS. The protocol provided the following
            features :

            1. Monitor charger status.
            2. Monitor battery status and condition.
            3. Monitor the utility status.
            4. Provide the power switch function for computer to turn on and
               off the utility on schedule for power saving.

            Computer will control information exchange by a query followed by
            <cr>. UPS will respond with information followed by a <cr> or
            action.

B. Hardware:

            BAUD RATE............... : 2400 bps
            DATA LENGTH.......... : 8 bits
            STOP BIT..................... : 1 bit
            PARITY........................ : NONE

            CABLING :

               COMPUTER                  UPS
            ===================================
                  RX   <----------   TX  (pin 9)
                  TX    ---------->  RX  (pin 6)
                  GND  <----------   GND (pin 7)

                  (9 pins female D-type connector)

C. COMMUNICATION PROTOCOL:

1. Status Inquiry:

Computer : Q1<cr>
        UPS      : UPS status data stream, such as
             (MMM.M NNN.N PPP.P QQQ RR.R S.SS TT.T  b7b6b5b4b3b2b1b0<cr>

        UPS status data stream :
	There should be a space character between every field for data
	separation. The meaning of each field is list as followed:

                a. Start byte    : (

		b.I/P voltage   : MMM.M
                  M is and integer number ranging from 0 to 9.
                  The unit is Volt.

                c.I/P fault voltage : NNN.N
                  N is and integer number ranging from 0 to 9.
                  The unit is Volt.

                  ** For OFF LINE UPS**

                    Its purpose is to identify a short duration voltage glitch
                  which cause OFF line UPS to go to Invter mode. If this occurs
                  input voltage will appear normal at query prior to glitch and
                  will still appear normal at next query.
                    The I/P fault voltage will hold glitch voltage till next
                  query. After query, the I/P fault voltage will be same as I/P
                  voltage until next glitch occurs.

                  ** For ON LINE UPS**

                    Its purpose is to identify a short duration utility fail
                  which cause ON line UPS to go to battery mode. If this occurs
                  input voltage will appear normal at query prior to fail and
                  will still appear normal at next query.
                    The I/P fault voltage will hold utility fail voltage till
                  next query. After query, the I/P voltage will be same as I/P
                  voltage until next utility fail occurs.

                d.O/P voltage   : PPP.P
                  P is an integer number ranging form 0 to 9.

                  The unit is Volt.

                e.O/P current   : QQQ
                  QQQ is a percent of maximum current, not an absolute value.

                f.I/P frequency : RR.R
                  R is an integer number ranging from 0 to 9.
                  The unit is HZ.

                g.Battery voltage : SS.S or S.SS
                  S is an integer number ranging from 0 to 9.
                    For on-line units battery voltage/cell is provided in the
                  form S.SS .
                    For standby units actual battery voltage is provided in
                  the form SS.S .
                    UPS type in UPS status will determine which reading was
                  obtained.

                h.Temperature   : TT.T
                  T is an integer number ranging form 0 to 9.
                  The unit is degree of centigrade.

                i.UPS Status    : <U>
                  <U> is one byte of binary information such as
                  <b7b6b5b4b3b2b1b0>.
 					Where bn is a ASCII character '0' or '1'.
.
UPS status :
Bit 	            Description                 	
 7  	1 : Utility Fail (Immediate)            	
 6  	1 : Battery Low                         	
 5  	1 : Bypass/Boost or Buck Active                 	
 4  	1 : UPS Failed                          	
 3  	1 : UPS Type is Standby (0 is On_line)  	
 2  	1 : Test in Progress                    	
 1  	1 : Shutdown Active                     	
 0  	1 : Beeper On                             	

j.Stop Byte     : <cr>

			Example: Computer : Q1<cr>
		    UPS      :
                         (208.4 140.0 208.4 034 59.9 2.05 35.0 00110000<cr>

                       Means    : I/P voltage is 208.4V.
                                  I/P fault voltage is 140.0V.
                                  O/P voltage is 208.4V.
                                  O/P current is 34 %.
                                  I/P frequency is 59.9 HZ.
                                  Battery voltage is 2.05V.
                                  Temperature is 35.0 degrees of centigrade.
                                  UPS type is on-line , UPS failed. Bypass
                                  active , and shutdown not active.

  2. Test for 10 seconds:

        Computer  : T<cr>
        UPS       : Test for 10 seconds and return to utility.

        If battery low occur during testing, UPS will return to
        utility immediately.

   3.Test until battery low :

        Computer  : TL<cr>
        UPS       : Test until battery low and return to utility.

   4.Test for specified time period :

        Computer  : T<n><cr>
        UPS       : Test for <n> minutes.

        a. During testing, UPS returns to utility immediately, if
           battery low occur.
        b. <n> is a number ranging from 01 to 99.

   5. Turn On/Off beep -- Toggle the UPS beeper :

        Computer  : Q<cr>

        When the AC power failed, UPS will generate a warning beep to
        inform the manager. Manager could toggle the warning beep by
        sending this command .

   6. Shutdown Command :

        Computer  : S<n><cr>
        UPS       : Shut UPS output off in <n> minutes.

        a. The UPS output will be off in <n> minutes, even if the
           utility power is present.
        b. If the battery low occurs before <n> minutes, the
           output is turned off immediately.
        c. After UPS shutdown, the controller of UPS monitors the
           utility power. If the utility is recovered, the UPS will wait
           for 10 seconds and connect the utility to output.
        d. <n> is a number ranging form .2, .3, ..., 01, 02, ..., up to 10.

        For example : S.3<cr> --- shut output off in (.3) minutes

   7. Shutdown and Restore Command :

        Computer  : S<n>R<m><cr>
        UPS       : Shut UPS output off in <n> minutes, and waiting
                    for <m> minutes then turn on UPS output again.

        a. The shutdown sequence is the same as the previous command.
           When the <m> minutes expired, the utility do not restore,
           the UPS will wait until utility restore.
        b. If UPS is in shutdown waiting state, the "C" command can
           let the shutdown procedure cancelled.
        c. If UPS is in restore waiting state, the "C" command can
           let the UPS output turned on, but UPS must be hold off at
           least 10 seconds. (if utility is present)
        d. <n> is a number ranging form .2, .3, ..., 01, 02, ..., up to 10.
        e. <m> is a number ranging form 0001 to 9999.

   8. Cancel Shutdown Command :

        Computer  : C<cr>
        UPS       : Cancel the SN<n><cr> and SN<n>R<m><cr> command.

        a. If UPS is in shut down waiting state, the shut down command
           is cancelled.
        b. If UPS is in restore waiting state, the UPS output is turned
           on, but UPS must be hold off at least 10 seconds.
           (if utility is present)

   9. Cancel Test Command :

        Computer  : CT<cr>
        UPS       : Cancel all test activity and connect the utility to
                    output immediately.

	10. UPS Information Command:

		Computer	: I<cr>
		UPS			: #Company_Name UPS_Model Version<cr>

	This function will make the UPS respond with the basic information
	about the company who manufacture the UPS, the model name of the
	UPS and the version number of the UPS firmware. The length of
	every field is listed as follows:
		Company_Name	: 15 characters, leave space if less than 15 characters
		UPS_Model		: 10 characters, leave space if less than 10 characters
		Version			: 10 characters, leave space if less than 10 characters
	
	There should be a space character between every field for separation.

	11. UPS Rating Information:
		
		Computer	: F<cr>
		UPS			: #MMM.M QQQ SS.SS RR.R<cr>

	This function makes the UPS answer the rating value of UPS. There
	should be a space character between every field for
	separation. The UPS's response contains the following information
	field:

			a. Rating Voltage	: MMM.M
			b. Rating Current	: QQQ
			c. Battery Voltage	: SS.SS or SSS.S
			d. Frequency		: RR.R

D. COMMAND SUMMARY:

ITEM	COMMAND 	           DESCRIPTION              	
 1a  	  D     	  Status Inquiry           *disable         	
 1  	  Q1     	  Status Inquiry                    	
 2  	  T     	  10 Seconds Test                   	
 3  	  TL    	  Test until Battery Low            	
 4  	  T<n>  	  Test for Specified Time Period    	
 5  	  Q     	  Turn On/Off beep                  	
 6  	  S<n>  	  Shut Down Command                 	
 7  	S<n>R<m>	  Shut Down and Restore Command     	
 8  	  C     	  Cancel Shut Down Command          	
 9  	  CT    	  Cancel Test Command               	
10	   I	  UPS Information Command	
11	   F	  UPS Rating Information	

E. Invalid Command/Information Handling

If the UPS receives any command that it could not handle, the UPS should
echo the received command back to the computer. The host should check if
the command send to UPS been echo or not. 
If there is any information field in the UPS's response which is
unavailable or not supported, the UPS should fill the field with '@'.
Notes by Russell Kroll, 4 April 2001:
S01R0001 and S01R0002 may not work on early firmware versions. The failure mode is that the UPS turns off and never returns. The fix is to push the return value up by 2, i.e. S01R0003, and it will return online properly.

```

I thought I'd mention it here, just in case you would consider it informative or relevan.
Apologies if this is well known and not of particular interest.
Maybe it could elevate the level of `ARMAC` compatibility on the website to ` known protocol`?

Finally, considering it's been some time since this PR, can one assume that the ARMAC devices such as the one listed above will still work in the latest versions?

Thank you so very much in advance!

**Comment by blaa** [comment]
Hm. That describes mostly the underlying protocol that is at least partially known already (?). I haven't changed it much. What I had problem with was how the serial protocol was encapsulated within the USB messages.  That's something that was a bit different (?) than with other drivers. So AFAIK I altered the USB decapsulation of serial protocol and currently NUT can manage to talk with it and tests it - what commands work and which don't.  

Mine still works in my setup, but I only have one. It has some quirks, like buttons that change something on the LCD that I don't know what causes as it wasn't documented. ;-) Like "Small char", "large char". Charging speed? Maaaybe? Dunno.  Seems to have some generic components (LCD) that are reused, and not everything is supposed to work with particular model. Mine has no passthrough too, which causes it to consume some power for itself all the time - and it gets a bit hot. But that's within spec.

I could help a bit if something doesn't work, but I don't have too much time nowadays. ;)

**Comment by jimklimov** [comment]
Circling back to this: I did not have the patience to compare *fully*, but the doc posted above does say it comes from NUT and looks like a formalized-markup reshuffle of https://github.com/networkupstools/nut-website/blob/3428a4545ebb4603ee7a35717e04dd5e7d1a44c3/protocols/megatec.txt

**Pull request merged**
