### PR TITLE
Add basic support for EVER USB-HID UPS

### PR DESCRIPTION
**Pull request by lsiudut**
UPDATE from PR review: This PR just extends mge-hid subdriver to recognize the ID of Ever UPS devices and so adding some level of practical support. There is an official driver in the works at #431 to take care about hardware related features.

-----

It was not recognized by default. Explore was showing though that NUT reads it properly.

Hardware details:
```
Bus 003 Device 002: ID 2e51:0000
```

Patched NUT output:
```
$ upsc ever@localhost
Init SSL without certificate database
battery.charge: 100
battery.runtime: 1668
battery.runtime.low: 100
battery.type: PbAc
device.mfr: EVER
device.model: ECO PRO AVR CDS
device.serial: [redacted]
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.parameter.vendorid: 2e51
driver.version: 2.7.4
driver.version.data: MGE HID 1.39
driver.version.internal: 0.41
outlet.1.status: on
output.current: 0.56
output.frequency: 50.1
output.voltage: 236.0
ups.delay.shutdown: 20
ups.load: 13
ups.mfr: EVER
ups.model: ECO PRO AVR CDS
ups.power: 132
ups.productid: 0000
ups.realpower: 86
ups.serial: [redacted]
ups.status: OL
ups.timer.shutdown: -1
ups.vendorid: 2e51
```

### CODE REVIEW

**Comment by zykh** [comment]
Thanks for the patch, @lsiudut.

Have you had a chance to test #431?

**Comment by lsiudut** [comment]
I'm the most horrible person for getting back to you so late, sorry!

Currently my UPS was sent to warranty for reasons. The PR you referenced looks very promising though - once I have it back I'll verify it and will get back to you ASAP.

Promise! ;-)

**Comment by jimklimov** [comment]
@lsiudut : did the device return from repairs? did you have a chance to test it against the "official" driver variant growing in #431? I am a bit reluctant to merge this hot-fix for adding a frankly unknown-quality support for the device as a generic HID UPS given that there may soon (...ish...) be better support taking actual HW capabilities into account.

Then again, maybe as a quick win this small PR can be merged (to have at least some compatibility quickly), and reverted (to avoid conflict) as part of #431 eventual completion. WDYT all? :)

**Comment by lsiudut** [comment]
Fair point, sorry for leaving it hanging for so long.

I use my custom build of nut atm, but will find some time in following days to test #431 . Seems promising to me :).

**Comment by vincentto13** [comment]
Hi, I was looking for support for EVER device support in NUT, and found this thread. I've verified both this PR, and #431 works for me. The only thing is that in #431 naming convention is perhaps not adequate. I've compared it against mge-hid driver, and seems there are no properly visible by Home Assistant, which is my primary usage. After contacting Ever support I was able to remap proper fields.

**Comment by jimklimov** [comment]
@vincentto13 : Regarding your comment that with help of Ever support you were able to remap fields, did that regard NUT standard field names (wrongly proposed as `ever.*` in PR #431) or some mappings for Home Assistant. If the former, an addition of that missing bit for completing and merging that PR for proper official support would be very welcome (wink) ;)

**Comment by mczerski** [comment]
I can confirm that this patch is also working for me, UPS EVER ECO PRO AVR CDS. The downside is that the status is very limited to what UPS is actually monitoring, e.g. input voltage is not reported but is available if checked with usbhid-ups with explore switch:
```
Path: UPS.PowerConverter.Input.Voltage, Type: Feature, ReportID: 0x15, Offset: 0, Size: 16, Value: 224
```

**Comment by jimklimov** [comment]
Should be overtaken by PR #431 (merged recently) so testing of current NUT master branch builds is very welcome. Note there was some guesswork to map existingd data points - fixes are also welcome if needed. :)

**Pull request closed without merging**
