### PR TITLE
docs/FAQ.txt: extend Q&A on "NUT proxying" with mention of "clone" driver

### PR DESCRIPTION
**Pull request by jimklimov**
Follows up in a way to #1196 so CC @tessus

### CODE REVIEW

**Comment by tessus** [comment]
Wow, ok. Another thing I did not know about. (It seems there are quite a lot of things I do not know when it comes to this project. ;-) )

However, I am not sure I entirely understand the purpose of using such a clone. It's basically just an alias, so why not use the original instead? The relay is clear to me, because it forwards/relays data.

But the clone makes no sense to me. Or at least from this explanation I don't understand why I would have to use such a clone. It is still a 1:1 relation so the only thing it hides is the name.

**Comment by jimklimov** [comment]
I believe historical rationale was to group load on a separately manageable
outlet or group of outlets on larger UPS and ePDUs, to power on/off
together. Maybe also to delegate for hosting/teams/....

**Comment by tessus** [comment]
@jimklimov out of curiosity... when are the html pages refreshed? I am just asking because other projects just use a git hub action after a PR has been merged.

**Comment by jimklimov** [comment]
What started as a short answer here, became a mailing-list post instead :)
https://alioth-lists.debian.net/pipermail/nut-upsuser/2021-December/012597.html

**Pull request merged**
