### PR TITLE
ups.conf/nutupsdrv: reword "user" directive section

### PR DESCRIPTION
**Pull request by aquette**
Thanks to Nash Kaminski for the base rewording

Reference: https://github.com/networkupstools/nut/pull/493
           https://github.com/networkupstools/nut/issues/336

Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>

### CODE REVIEW

**Comment by clepple** [comment]
The sentence about drivers starting as root is probably more confusing than helpful. While the driver starts as root, it changes to a less-privileged user ID by default, even if `-u` is not provided.

**Comment by aquette** [comment]
@clepple: so do you think that the wording in this PR fix this?

**Comment by clepple** [comment]
@aquette no, as mentioned [originally](
https://github.com/networkupstools/nut/issues/336#issue-185915778), I think it is important to point out that the `user` argument to the driver is optional, and overrides the built-in unprivileged user ID. I'll see if I can come up with something later.

**Comment by clepple** [comment]
Still working on it, but I'm looking at something like this:
```
*-u* 'username'::
Override the unprivileged username that the driver may use after startup.
If started as root, the driver will look up 'username' in the `passwd` 
database, then change to the user and group identities associated with
'username'. (If started with a nonzero UID or effective UID, the driver will 
silently ignore this option.)
+
When compiling NUT from source, the default username is typically `nobody`, and 
this may cause permission errors when the driver opens the UPS device node. You 
can use this option to temporarily override the defaults. For testing purposes,
you can set this option to `root` to bypass permission errors, especially with
USB-based drivers. However, you will want to remove this option later in order
to avoid permission conflicts between the driver and the unprivileged copy of 
linkman:upsd[8].
```

**Pull request closed without merging**
