### PR TITLE
libupsclient, libnutscan: Only export symbols part of the public API

### PR DESCRIPTION
**Pull request by bigon**
Fixes: #713

### CODE REVIEW

**Comment by bigon** [comment]
This works on my machine, but I'm not sure that `-export-symbols-regex` is available on all platform

Not sure how to do that for C++ library

**Comment by bigon** [comment]
Any comments on this?

**Comment by zykh** [comment]
Perhaps, we should also bump the various versions... once per release should be fine, later today, I'll add a note so that we don't forget to do that (if we ever get to the next release).

Note to future self: fix the conflict in the `libusb-compat-1.0` branch (I used that option, too, but just to filter-out the libusb_* symbols in libnutscan, no longer necessary with this PR).

(yeah, I'm not dead yet - but I'm working on it)

**Comment by zykh** [comment]
...so, @aquette, @jimklimov, nihil obstat?

**Comment by aquette** [comment]
@zykh I let you manage this one, thanks

**Review by jimklimov — APPROVED** [review]

**Pull request merged**
