### PR TITLE
drivers/generic_modbus.{c,h}: fix compilation warnings

### PR DESCRIPTION
**Pull request by jimklimov**
Follows up from #1052 to clean up compilation warnings.

CC @dtsecon - in original PR I asked whether generic types like "int" should become specific-bitness types to match wire protocol, etc.? If there is something to fix, please base that over this cleaned-up code :)

Also, `ser_parity` is not sanity-checked (at least when received from config); should it be? Any others?

UPDATE: CI likes the change so I'll merge it now; feel free to post further PRs based on NUT master branch.

### CODE REVIEW

**Comment by jimklimov** [comment]
Also if possible, can you test the updated driver in master branch against your device, to make sure I did not add typos etc?

**Comment by dtsecon** [comment]
I'm sorry for my delayed response. I didn't have the chance to review the committed changes due to my involvement in other business activities. I will check and give some feedback

**Comment by dtsecon** [comment]
I have done some testing based on code from master branch. It seems to work fine, however I've made some **improvements**. Driver now handles connection errors (broken pipe) with modbus tcp server devices. I noticed also that there might be cases with modbus tcp devices, where invalid data are received (shifted data frames) due to tight time intervals between requests. So I've added some code to configure the response time out between requests and between frame bytes. The new code is under testing. When it's done should I commit these modifications within this PR?

**Comment by jimklimov** [comment]
Yes, thanks, a PR would be great!

**Comment by dtsecon** [comment]
I have tested the code and committed the changes into the current fork (PR). Is that ok or should I open a new PR?

**Comment by jimklimov** [comment]
If you mean #1239, that looks OK (further comments pursued there).

If the question is about methodology - you can make many PRs at once from
same fork using different branches, and re-use those branches to iterate on
a subject, but only after an initial PR from such branch got merged and
GitHub no longer tracks it as a source of contributions.

**Pull request merged**
