### PR TITLE
Add a product ID for APC AP9584 USB kit.

### PR DESCRIPTION
**Pull request by runderwo**
Add a product ID for APC AP9584 USB kit.

### CODE REVIEW

**Comment by clepple** [comment]
> Add a product ID for APC AP9584 USB kit.

Does this kit work with usbhid-ups as well?

The file you patched is auto-generated from several driver source files, so if possible I would like to add it to usbhid-ups (apc-hid.c). =

**Comment by runderwo** [comment]
Yes, it works with usbhid-ups.  The only problem was the product ID not being mapped, so the device node permissions were wrong.  I'll add it to the other file instead.

**Comment by runderwo** [comment]
Okay, I added it to apc-hid.c and checked that the rules are auto-generated correctly.
fyi, this is the lsusb -v output for this adapter:

Bus 001 Device 002: ID 051d:0000 American Power Conversion
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x051d American Power Conversion
  idProduct          0x0000
  bcdDevice            0.06
  iManufacturer           3 American Power Conversion
  iProduct                1 APC UPS USB FW:2
  iSerial                 2
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration         11 1
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               30mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      0 None
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     343
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval             100
Device Status:     0x0001
  Self Powered

**Comment by clepple** [comment]
Thanks. What does `upsc` show for this adapter?

**Comment by runderwo** [comment]
$ upsc apcsmart@localhost
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.date: 2065/165/165
battery.runtime: 0
battery.type: PbAc
battery.voltage: 12.0
battery.voltage.nominal: 12.0
device.mfr: American Power Conversion 
device.model: APC UPS USB
device.serial:  
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.productid: 0000
driver.parameter.vendorid: 051d
driver.version: 2.6.4
driver.version.data: APC HID 0.95
driver.version.internal: 0.37
ups.firmware: 2 
ups.mfr: American Power Conversion 
ups.mfr.date: not set
ups.model: APC UPS USB
ups.productid: 0000
ups.serial:  
ups.status: OL
ups.timer.reboot: 0
ups.vendorid: 051d

**Comment by runderwo** [comment]
It's connected to a Smart-UPS 1500.

**Pull request closed without merging**
