### PR TITLE
Add usb_resetter documentation for unreliable USB UPS interfaces (Linux, Python)

### PR DESCRIPTION
**Pull request by deajan**
This PR adds documentation for a workaround solution for unreliable USB interfaces, as stated in #1688 
I use this on a couple of UPS for months now, without any major issue.

## General points

- [X] Described the changes in the PR submission or a separate issue, e.g.
  known published or discovered protocols, applicable hardware (expected
  compatible and actually tested/developed against), limitations, etc.

- [X] There may be multiple commits in the PR, aligned and commented with
  a functional change. Notably, coding style changes better belong in a
  separate PR, but certainly in a dedicated commit to simplify reviews
  of "real" changes in the other commits. Similarly for typo fixes in
  comments or text documents.

## General documentation updates

- [N/A] Updated `docs/acknowledgements.txt` (for vendor-backed device support)

- [N/A] Added or updated manual page information in `docs/man/*.txt` files
  and corresponding recipe lists in `docs/man/Makefile.am` for new pages

- [N/A] Passed `make spellcheck`, updated spell-checking dictionary in the
  `docs/nut.dict` file if needed (did not remove any words -- the `make`
  rule printout in case of changes suggests how to maintain it).

### CODE REVIEW

**Comment by deajan** [comment]
> I think it is worth noting (maybe in the document too) that nut-driver.service provided here is an example

Indeed, I'll have another PR for the README file

> The call to usb_resetter can be a systemd drop-in file for the particular device

I have looked at drop-in files, but i don't know how to limit to one instance of a `@.service file`

> Does the script only exit when it is sure the device is usable, or should there be an artificial delay added?

No, the script's task is only to reset devices / controllers.  
Nevertheless, I did not have to set any arbitrary wait time to make use of my USB UPSes with NUT.

**Comment by jimklimov** [comment]
> don't know how to limit to one instance of a @.service file

Just name its directory for the expected instance (NDE with NUT v2.8.0+ will create some drop-ins), e.g.

/etc/systemd/system/nut-driver@myups.service.d/dropin.conf

**Comment by jimklimov** [comment]
As a curious data point, similar issue (and also with Innotech chips) was addressed for Solaris/illumos earlier, see https://github.com/networkupstools/nut/blob/master/docs/solaris-usb.txt#L233 and https://github.com/networkupstools/nut/blob/master/scripts/Solaris/reset-ups-usb-solaris.sh.sample

**Comment by jimklimov** [comment]
Thanks!

**Pull request merged**
