### PR TITLE
Update liebert-hid.c

### PR DESCRIPTION
**Pull request by gprints**
- Increased precision for battery voltage
- Added support for some more variables found via
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
   0.000000     debug level is '2'
   0.002117     upsdrv_initups...
   0.002669     Checking device (06DA/FFFF) (/dev/usb//dev/ugen0.2)
   0.466604     - VendorID: 06da
   0.466640     - ProductID: ffff
   0.466650     - Manufacturer: PPC
   0.466658     - Product: HID UPS
   0.466668     - Serial Number: Blank
   0.466676     - Bus: /dev/usb
   0.466684     - Device release number: 0100
   0.466694     Trying to match device
   0.466715     Device matches
   0.519650     HID descriptor length 1529
   3.177591     Report Descriptor size = 1529
   3.178933     Using subdriver: Phoenixtec/Liebert HID 0.3
   3.178957     156 HID objects found
   3.206612     Path: UPS.BatterySystem.Battery.AudibleAlarmControl, Type: Feature, ReportID: 0x28, Offset: 0, Size: 8, Value: 2
   3.244628     Path: UPS.BatterySystem.Battery.BatteryID, Type: Feature, ReportID: 0x20, Offset: 0, Size: 8, Value: 1
   3.278627     Path: UPS.BatterySystem.Battery.ffff0049, Type: Feature, ReportID: 0x22, Offset: 0, Size: 8, Value: 1
   3.317631     Path: UPS.BatterySystem.Battery.DesignCapacity, Type: Feature, ReportID: 0x23, Offset: 0, Size: 32, Value: 32400
   3.356656     Path: UPS.BatterySystem.Battery.PresentStatus.Present, Type: Feature, ReportID: 0x27, Offset: 0, Size: 8, Value: 1
   3.356710     Path: UPS.BatterySystem.Battery.PresentStatus.Present, Type: Input, ReportID: 0x27, Offset: 0, Size: 8, Value: 1
   3.386621     Path: UPS.BatterySystem.Battery.Test, Type: Feature, ReportID: 0x24, Offset: 0, Size: 8, Value: 1
   3.425776     Path: UPS.BatterySystem.Battery.ffff0045, Type: Feature, ReportID: 0x25, Offset: 0, Size: 32, Value: 604800
   3.425914     Path: UPS.BatterySystem.BatterySystemID, Type: Feature, ReportID: 0x20, Offset: 8, Size: 8, Value: 1
   3.458618     Path: UPS.BatterySystem.Charger.ffff0087, Type: Feature, ReportID: 0x29, Offset: 0, Size: 8, Value: 1
   3.458665     Path: UPS.BatterySystem.Charger.ChargerID, Type: Feature, ReportID: 0x20, Offset: 16, Size: 8, Value: 1
   3.495627     Path: UPS.BatterySystem.Charger.ffff006b, Type: Feature, ReportID: 0x26, Offset: 0, Size: 8, Value: 4
   3.495672     Path: UPS.BatterySystem.Charger.ffff0094, Type: Feature, ReportID: 0x26, Offset: 8, Size: 8, Value: 4
   3.495699     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0079, Type: Feature, ReportID: 0x27, Offset: 8, Size: 8, Value: 1
   3.495731     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0079, Type: Input, ReportID: 0x27, Offset: 8, Size: 8, Value: 1
   3.495757     Path: UPS.BatterySystem.Charger.PresentStatus.InternalFailure, Type: Feature, ReportID: 0x27, Offset: 16, Size: 8, Value: 0
   3.495783     Path: UPS.BatterySystem.Charger.PresentStatus.InternalFailure, Type: Input, ReportID: 0x27, Offset: 16, Size: 8, Value: 0
   3.495808     Path: UPS.BatterySystem.Charger.PresentStatus.Used, Type: Feature, ReportID: 0x27, Offset: 24, Size: 8, Value: 1
   3.495833     Path: UPS.BatterySystem.Charger.PresentStatus.Used, Type: Input, ReportID: 0x27, Offset: 24, Size: 8, Value: 1
   3.495858     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0074, Type: Feature, ReportID: 0x27, Offset: 32, Size: 8, Value: 0
   3.495883     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0074, Type: Input, ReportID: 0x27, Offset: 32, Size: 8, Value: 0
   3.495908     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0075, Type: Feature, ReportID: 0x27, Offset: 40, Size: 8, Value: 0
   3.495933     Path: UPS.BatterySystem.Charger.PresentStatus.ffff0075, Type: Input, ReportID: 0x27, Offset: 40, Size: 8, Value: 0
   8.499465     libusb_get_report: Unknown error
   8.499614     Can't retrieve Report fe: Input/output error
   8.499636     Path: UPS.ffff00e0, Type: Feature, ReportID: 0xfe, Offset: 0, Size: 8
   8.535609     refresh_report_buffer: expected 33 bytes, but got 4 instead
   8.535699     Path: UPS.ffff00e0, Type: Feature, ReportID: 0xff, Offset: 0, Size: 8, Value: 1
   8.569631     Path: UPS.Flow.[1].ConfigFrequency, Type: Feature, ReportID: 0x14, Offset: 0, Size: 8, Value: 50
   8.606588     Path: UPS.Flow.[1].ConfigVoltage, Type: Feature, ReportID: 0x15, Offset: 0, Size: 16, Value: 230
   8.646632     Path: UPS.Flow.[1].FlowID, Type: Feature, ReportID: 0x0b, Offset: 0, Size: 8, Value: 1
   8.678617     Path: UPS.Flow.[4].ConfigActivePower, Type: Feature, ReportID: 0x74, Offset: 0, Size: 16, Value: 500
   8.714633     Path: UPS.Flow.[4].ConfigApparentPower, Type: Feature, ReportID: 0x75, Offset: 0, Size: 16, Value: 750
   8.751633     Path: UPS.Flow.[4].ConfigFrequency, Type: Feature, ReportID: 0x0d, Offset: 0, Size: 8, Value: 50
   8.785635     Path: UPS.Flow.[4].ConfigPercentLoad, Type: Feature, ReportID: 0x16, Offset: 0, Size: 8, Value: 105
   8.822616     Path: UPS.Flow.[4].ConfigVoltage, Type: Feature, ReportID: 0x72, Offset: 0, Size: 16, Value: 230
   8.822666     Path: UPS.Flow.[4].FlowID, Type: Feature, ReportID: 0x0b, Offset: 8, Size: 8, Value: 4
   8.904693     Path: UPS.ffff001c.ffff001e.[1].ffff0098, Type: Feature, ReportID: 0x71, Offset: 0, Size: 16, Value: 2056
   8.904762     Path: UPS.ffff001c.ffff001e.[2].ffff0098, Type: Feature, ReportID: 0x71, Offset: 16, Size: 16, Value: 0
   8.904807     Path: UPS.ffff001c.ffff001e.[3].ffff0098, Type: Feature, ReportID: 0x71, Offset: 32, Size: 16, Value: 0
   8.904851     Path: UPS.ffff001c.ffff001e.[4].ffff0098, Type: Feature, ReportID: 0x71, Offset: 48, Size: 16, Value: 0
   8.904894     Path: UPS.ffff001c.ffff001e.[5].ffff0098, Type: Feature, ReportID: 0x71, Offset: 64, Size: 16, Value: 0
   8.904937     Path: UPS.ffff001c.ffff001e.[6].ffff0098, Type: Feature, ReportID: 0x71, Offset: 80, Size: 16, Value: 0
   8.904980     Path: UPS.ffff001c.ffff001e.[7].ffff0098, Type: Feature, ReportID: 0x71, Offset: 96, Size: 16, Value: 0
   8.905024     Path: UPS.ffff001c.ffff001e.[8].ffff0098, Type: Feature, ReportID: 0x71, Offset: 112, Size: 16, Value: 0
   8.905090     Path: UPS.ffff001c.ffff001e.[9].ffff0098, Type: Feature, ReportID: 0x71, Offset: 128, Size: 16, Value: 0
   8.905138     Path: UPS.ffff001c.ffff001e.[10].ffff0098, Type: Feature, ReportID: 0x71, Offset: 144, Size: 16, Value: 0
   8.905288     Path: UPS.ffff001c.ffff001e.[11].ffff0098, Type: Feature, ReportID: 0x71, Offset: 160, Size: 16, Value: 0
   8.905342     Path: UPS.ffff001c.ffff001e.[12].ffff0098, Type: Feature, ReportID: 0x71, Offset: 176, Size: 16, Value: 0
   8.905401     Path: UPS.ffff001c.ffff001e.[13].ffff0098, Type: Feature, ReportID: 0x71, Offset: 192, Size: 16, Value: 0
   8.905444     Path: UPS.ffff001c.ffff001e.[14].ffff0098, Type: Feature, ReportID: 0x71, Offset: 208, Size: 16, Value: 0
   8.905488     Path: UPS.ffff001c.ffff001e.[15].ffff0098, Type: Feature, ReportID: 0x71, Offset: 224, Size: 16, Value: 0
   8.950661     Path: UPS.OutletSystem.Outlet.[1].FlowID, Type: Feature, ReportID: 0x80, Offset: 0, Size: 8, Value: 4
   8.950709     Path: UPS.OutletSystem.Outlet.[1].OutletID, Type: Feature, ReportID: 0x80, Offset: 8, Size: 8, Value: 0
   8.983638     Path: UPS.OutletSystem.Outlet.[1].PresentStatus.Switchable, Type: Feature, ReportID: 0x81, Offset: 0, Size: 8, Value: 0
   8.983683     Path: UPS.OutletSystem.OutletSystemID, Type: Feature, ReportID: 0x80, Offset: 16, Size: 8, Value: 1
   9.019630     Path: UPS.PowerConverter.ffff0041, Type: Feature, ReportID: 0x4a, Offset: 0, Size: 8, Value: 1
   9.055643     Path: UPS.PowerConverter.Input.[1].ffff0043, Type: Feature, ReportID: 0x73, Offset: 0, Size: 8, Value: 1
   9.097634     Path: UPS.PowerConverter.Input.[1].Current, Type: Feature, ReportID: 0x31, Offset: 0, Size: 16, Value: 0
   9.131678     Path: UPS.PowerConverter.Input.[1].FlowID, Type: Feature, ReportID: 0x30, Offset: 0, Size: 8, Value: 1
   9.131729     Path: UPS.PowerConverter.Input.[1].Frequency, Type: Feature, ReportID: 0x31, Offset: 16, Size: 16, Value: 49.9
   9.131755     Path: UPS.PowerConverter.Input.[1].InputID, Type: Feature, ReportID: 0x30, Offset: 8, Size: 8, Value: 1
   9.170638     Path: UPS.PowerConverter.Input.[1].PresentStatus.Boost, Type: Feature, ReportID: 0x32, Offset: 0, Size: 8, Value: 0
   9.170689     Path: UPS.PowerConverter.Input.[1].PresentStatus.Boost, Type: Input, ReportID: 0x32, Offset: 0, Size: 8, Value: 0
   9.170718     Path: UPS.PowerConverter.Input.[1].PresentStatus.Buck, Type: Feature, ReportID: 0x32, Offset: 8, Size: 8, Value: 0
   9.170746     Path: UPS.PowerConverter.Input.[1].PresentStatus.Buck, Type: Input, ReportID: 0x32, Offset: 8, Size: 8, Value: 0
   9.170782     Path: UPS.PowerConverter.Input.[1].PresentStatus.FrequencyOutOfRange, Type: Feature, ReportID: 0x32, Offset: 16, Size: 8, Value: 0
   9.170810     Path: UPS.PowerConverter.Input.[1].PresentStatus.FrequencyOutOfRange, Type: Input, ReportID: 0x32, Offset: 16, Size: 8, Value: 0
   9.170838     Path: UPS.PowerConverter.Input.[1].PresentStatus.InternalFailure, Type: Feature, ReportID: 0x32, Offset: 24, Size: 8, Value: 0
   9.170865     Path: UPS.PowerConverter.Input.[1].PresentStatus.InternalFailure, Type: Input, ReportID: 0x32, Offset: 24, Size: 8, Value: 0
   9.170892     Path: UPS.PowerConverter.Input.[1].PresentStatus.Used, Type: Feature, ReportID: 0x32, Offset: 32, Size: 8, Value: 1
   9.170920     Path: UPS.PowerConverter.Input.[1].PresentStatus.Used, Type: Input, ReportID: 0x32, Offset: 32, Size: 8, Value: 1
   9.170948     Path: UPS.PowerConverter.Input.[1].PresentStatus.VoltageOutOfRange, Type: Feature, ReportID: 0x32, Offset: 40, Size: 8, Value: 0
   9.170975     Path: UPS.PowerConverter.Input.[1].PresentStatus.VoltageOutOfRange, Type: Input, ReportID: 0x32, Offset: 40, Size: 8, Value: 0
   9.171003     Path: UPS.PowerConverter.Input.[1].PresentStatus.ffff0078, Type: Feature, ReportID: 0x32, Offset: 48, Size: 8, Value: 0
   9.171032     Path: UPS.PowerConverter.Input.[1].PresentStatus.ffff0078, Type: Input, ReportID: 0x32, Offset: 48, Size: 8, Value: 0
   9.171092     Path: UPS.PowerConverter.Input.[1].Voltage, Type: Feature, ReportID: 0x31, Offset: 32, Size: 16, Value: 236.7
   9.199642     Path: UPS.PowerConverter.Input.[3].ConfigPercentLoad, Type: Feature, ReportID: 0x3c, Offset: 0, Size: 8, Value: 10
   9.235674     Path: UPS.PowerConverter.Input.[3].ffff0072, Type: Feature, ReportID: 0x3e, Offset: 0, Size: 8, Value: 0
   9.271632     Path: UPS.PowerConverter.Input.[3].ffff0046, Type: Feature, ReportID: 0x39, Offset: 0, Size: 8, Value: 0
   9.271681     Path: UPS.PowerConverter.Input.[3].FlowID, Type: Feature, ReportID: 0x30, Offset: 16, Size: 8, Value: 3
   9.271706     Path: UPS.PowerConverter.Input.[3].InputID, Type: Feature, ReportID: 0x30, Offset: 24, Size: 8, Value: 3
   9.307632     Path: UPS.PowerConverter.Input.[3].PresentStatus.Used, Type: Feature, ReportID: 0x3b, Offset: 0, Size: 8, Value: 0
   9.307678     Path: UPS.PowerConverter.Input.[3].PresentStatus.Used, Type: Input, ReportID: 0x3b, Offset: 0, Size: 8, Value: 0
   9.344637     Path: UPS.PowerConverter.Input.[3].ffff005d, Type: Feature, ReportID: 0x3d, Offset: 0, Size: 16, Value: 300
   9.379633     Path: UPS.PowerConverter.Input.[3].ffff0047, Type: Feature, ReportID: 0x3a, Offset: 0, Size: 8, Value: 1
   9.415641     Path: UPS.PowerConverter.ffff0014.PresentStatus.Used, Type: Feature, ReportID: 0x41, Offset: 0, Size: 8, Value: 0
   9.415689     Path: UPS.PowerConverter.ffff0014.PresentStatus.Used, Type: Input, ReportID: 0x41, Offset: 0, Size: 8, Value: 0
   9.468622     Path: UPS.PowerConverter.Output.ActivePower, Type: Feature, ReportID: 0x42, Offset: 0, Size: 16, Value: 50
   9.468673     Path: UPS.PowerConverter.Output.ApparentPower, Type: Feature, ReportID: 0x42, Offset: 16, Size: 16, Value: 71
   9.468704     Path: UPS.PowerConverter.Output.Current, Type: Feature, ReportID: 0x42, Offset: 32, Size: 16, Value: 0.3
   9.468734     Path: UPS.PowerConverter.Output.ffff0086, Type: Feature, ReportID: 0x42, Offset: 48, Size: 8, Value: 54
   9.507631     Path: UPS.PowerConverter.Output.FlowID, Type: Feature, ReportID: 0x40, Offset: 0, Size: 8, Value: 4
   9.541634     Path: UPS.PowerConverter.Output.ffff0044, Type: Feature, ReportID: 0x43, Offset: 0, Size: 8, Value: 1
   9.541685     Path: UPS.PowerConverter.Output.Frequency, Type: Feature, ReportID: 0x42, Offset: 56, Size: 16, Value: 49.9
   9.578631     Path: UPS.PowerConverter.Output.ffff0053, Type: Feature, ReportID: 0x4d, Offset: 0, Size: 16, Value: 243
   9.614614     Path: UPS.PowerConverter.Output.HighVoltageTransfer, Type: Feature, ReportID: 0x48, Offset: 0, Size: 16, Value: 276
   9.650987     Path: UPS.PowerConverter.Output.ffff0050, Type: Feature, ReportID: 0x4e, Offset: 0, Size: 16, Value: 207
   9.686616     Path: UPS.PowerConverter.Output.LowVoltageTransfer, Type: Feature, ReportID: 0x47, Offset: 0, Size: 16, Value: 184
   9.686661     Path: UPS.PowerConverter.Output.OutputID, Type: Feature, ReportID: 0x40, Offset: 8, Size: 8, Value: 1
   9.686690     Path: UPS.PowerConverter.Output.ffff0069, Type: Feature, ReportID: 0x42, Offset: 72, Size: 8, Value: 70
   9.721663     Path: UPS.PowerConverter.Output.PresentStatus.ffff004a, Type: Feature, ReportID: 0x49, Offset: 0, Size: 8, Value: 0
   9.721710     Path: UPS.PowerConverter.Output.PresentStatus.ffff004a, Type: Input, ReportID: 0x49, Offset: 0, Size: 8, Value: 0
   9.757629     Path: UPS.PowerConverter.Output.ffff004c, Type: Feature, ReportID: 0x4f, Offset: 0, Size: 8, Value: 0
   9.757683     Path: UPS.PowerConverter.Output.Voltage, Type: Feature, ReportID: 0x42, Offset: 80, Size: 16, Value: 236.7
   9.757705     Path: UPS.PowerConverter.PowerConverterID, Type: Feature, ReportID: 0x40, Offset: 16, Size: 8, Value: 1
   9.793632     Path: UPS.PowerSummary.AudibleAlarmControl, Type: Feature, ReportID: 0x13, Offset: 0, Size: 8, Value: 2
   9.832635     Path: UPS.PowerSummary.CapacityGranularity1, Type: Feature, ReportID: 0x0c, Offset: 0, Size: 8, Value: 1
   9.832680     Path: UPS.PowerSummary.CapacityMode, Type: Feature, ReportID: 0x0c, Offset: 8, Size: 8, Value: 2
   9.832702     Path: UPS.PowerSummary.ConfigVoltage, Type: Feature, ReportID: 0x0d, Offset: 8, Size: 16, Value: 12
   9.832725     Path: UPS.PowerSummary.ffff0095, Type: Feature, ReportID: 0x0b, Offset: 16, Size: 8, Value: 0
   9.868637     Path: UPS.PowerSummary.DelayBeforeShutdown, Type: Feature, ReportID: 0x09, Offset: 0, Size: 32, Value: 0
   9.904633     Path: UPS.PowerSummary.DelayBeforeStartup, Type: Feature, ReportID: 0x0a, Offset: 0, Size: 32, Value: 0
   9.904680     Path: UPS.PowerSummary.DesignCapacity, Type: Feature, ReportID: 0x0c, Offset: 16, Size: 8, Value: 100
   9.904703     Path: UPS.PowerSummary.FlowID, Type: Feature, ReportID: 0x0b, Offset: 24, Size: 8, Value: 4
   9.904725     Path: UPS.PowerSummary.FullChargeCapacity, Type: Feature, ReportID: 0x0c, Offset: 24, Size: 8, Value: 100
   9.944636     Path: UPS.PowerSummary.iDeviceChemistry, Type: Feature, ReportID: 0x10, Offset: 0, Size: 8, Value: 4
   9.944682     Path: UPS.PowerSummary.iManufacturer, Type: Feature, ReportID: 0x10, Offset: 8, Size: 8, Value: 1
   9.944706     Path: UPS.PowerSummary.ffff00f0, Type: Feature, ReportID: 0x10, Offset: 16, Size: 8, Value: 7
   9.944730     Path: UPS.PowerSummary.ffff00f3, Type: Feature, ReportID: 0x10, Offset: 24, Size: 8, Value: 15
   9.944754     Path: UPS.PowerSummary.iProduct, Type: Feature, ReportID: 0x10, Offset: 32, Size: 8, Value: 2
   9.944777     Path: UPS.PowerSummary.iSerialNumber, Type: Feature, ReportID: 0x10, Offset: 40, Size: 8, Value: 3
   9.944801     Path: UPS.PowerSummary.ffff00f1, Type: Feature, ReportID: 0x10, Offset: 48, Size: 8, Value: 5
   9.973630     Path: UPS.PowerSummary.ffff00e2, Type: Feature, ReportID: 0xe2, Offset: 0, Size: 8, Value: 29
  10.011631     Path: UPS.PowerSummary.PercentLoad, Type: Feature, ReportID: 0x07, Offset: 0, Size: 8, Value: 10
  10.011676     Path: UPS.PowerSummary.PowerSummaryID, Type: Feature, ReportID: 0x0b, Offset: 32, Size: 8, Value: 1
  10.050637     Path: UPS.PowerSummary.PresentStatus.ACPresent, Type: Feature, ReportID: 0x01, Offset: 0, Size: 8, Value: 1
  10.050684     Path: UPS.PowerSummary.PresentStatus.BelowRemainingCapacityLimit, Type: Feature, ReportID: 0x01, Offset: 8, Size: 8, Value: 0
  10.050709     Path: UPS.PowerSummary.PresentStatus.Charging, Type: Feature, ReportID: 0x01, Offset: 16, Size: 8, Value: 1
  10.081629     Path: UPS.PowerSummary.PresentStatus.CommunicationLost, Type: Feature, ReportID: 0x0f, Offset: 0, Size: 8, Value: 0
  10.081674     Path: UPS.PowerSummary.PresentStatus.CommunicationLost, Type: Input, ReportID: 0x0f, Offset: 0, Size: 8, Value: 0
  10.121634     Path: UPS.PowerSummary.PresentStatus.ffff002d, Type: Feature, ReportID: 0x03, Offset: 0, Size: 8, Value: 0
  10.121682     Path: UPS.PowerSummary.PresentStatus.ffff002d, Type: Input, ReportID: 0x03, Offset: 0, Size: 8, Value: 0
  10.121706     Path: UPS.PowerSummary.PresentStatus.Discharging, Type: Feature, ReportID: 0x01, Offset: 24, Size: 8, Value: 0
  10.121729     Path: UPS.PowerSummary.PresentStatus.ffff0068, Type: Feature, ReportID: 0x03, Offset: 8, Size: 8, Value: 0
  10.121752     Path: UPS.PowerSummary.PresentStatus.ffff0068, Type: Input, ReportID: 0x03, Offset: 8, Size: 8, Value: 0
  10.121774     Path: UPS.PowerSummary.PresentStatus.ffff0077, Type: Feature, ReportID: 0x03, Offset: 16, Size: 8, Value: 0
  10.121797     Path: UPS.PowerSummary.PresentStatus.ffff0077, Type: Input, ReportID: 0x03, Offset: 16, Size: 8, Value: 0
  10.121820     Path: UPS.PowerSummary.PresentStatus.Good, Type: Feature, ReportID: 0x01, Offset: 32, Size: 8, Value: 1
  10.156676     Path: UPS.PowerSummary.PresentStatus.InternalFailure, Type: Feature, ReportID: 0x02, Offset: 0, Size: 8, Value: 0
  10.156724     Path: UPS.PowerSummary.PresentStatus.InternalFailure, Type: Input, ReportID: 0x02, Offset: 0, Size: 8, Value: 0
  10.156748     Path: UPS.PowerSummary.PresentStatus.NeedReplacement, Type: Feature, ReportID: 0x02, Offset: 8, Size: 8, Value: 0
  10.156771     Path: UPS.PowerSummary.PresentStatus.NeedReplacement, Type: Input, ReportID: 0x02, Offset: 8, Size: 8, Value: 0
  10.156794     Path: UPS.PowerSummary.PresentStatus.Overload, Type: Feature, ReportID: 0x02, Offset: 16, Size: 8, Value: 0
  10.156817     Path: UPS.PowerSummary.PresentStatus.Overload, Type: Input, ReportID: 0x02, Offset: 16, Size: 8, Value: 0
  10.156839     Path: UPS.PowerSummary.PresentStatus.OverTemperature, Type: Feature, ReportID: 0x03, Offset: 24, Size: 8, Value: 0
  10.156861     Path: UPS.PowerSummary.PresentStatus.OverTemperature, Type: Input, ReportID: 0x03, Offset: 24, Size: 8, Value: 0
  10.156887     Path: UPS.PowerSummary.PresentStatus.ShutdownImminent, Type: Feature, ReportID: 0x02, Offset: 24, Size: 8, Value: 0
  10.156909     Path: UPS.PowerSummary.PresentStatus.ShutdownImminent, Type: Input, ReportID: 0x02, Offset: 24, Size: 8, Value: 0
  10.189641     Path: UPS.PowerSummary.PresentStatus.Switchable, Type: Feature, ReportID: 0x05, Offset: 0, Size: 8, Value: 1
  10.189684     Path: UPS.PowerSummary.PresentStatus.Switchable, Type: Input, ReportID: 0x05, Offset: 0, Size: 8, Value: 1
  10.230616     Path: UPS.PowerSummary.RemainingCapacity, Type: Feature, ReportID: 0x06, Offset: 0, Size: 8, Value: 100
  10.261632     Path: UPS.PowerSummary.RemainingCapacityLimit, Type: Feature, ReportID: 0x08, Offset: 0, Size: 8, Value: 20
  10.297633     Path: UPS.PowerSummary.ffff004d, Type: Feature, ReportID: 0x12, Offset: 0, Size: 8, Value: 20
  10.333631     Path: UPS.PowerSummary.ffff005f, Type: Feature, ReportID: 0x0e, Offset: 0, Size: 8, Value: 0
  10.333678     Path: UPS.PowerSummary.RunTimeToEmpty, Type: Feature, ReportID: 0x06, Offset: 8, Size: 32, Value: 2971
  10.369631     Path: UPS.PowerSummary.ffff0048, Type: Feature, ReportID: 0x11, Offset: 0, Size: 8, Value: 0
  10.408642     Path: UPS.PowerSummary.ffff0091, Type: Feature, ReportID: 0x18, Offset: 0, Size: 32, Value: 183600
  10.408688     Path: UPS.PowerSummary.Voltage, Type: Feature, ReportID: 0x07, Offset: 8, Size: 16, Value: 13.1
  10.408750     Report descriptor retrieved (Reportlen = 1529)
  10.408759     Found HID device
  10.408769     Detected a UPS: PPC/HID UPS
  10.408874     Path: UPS.PowerSummary.Voltage, Type: Feature, ReportID: 0x07, Offset: 8, Size: 16, Value: 13.1
  10.443632     Path: UPS.PowerSummary.ConfigVoltage, Type: Feature, ReportID: 0x0d, Offset: 8, Size: 16, Value: 12
  10.443734     Path: UPS.PowerSummary.RemainingCapacity, Type: Feature, ReportID: 0x06, Offset: 0, Size: 8, Value: 100
  10.443792     Path: UPS.PowerSummary.RunTimeToEmpty, Type: Feature, ReportID: 0x06, Offset: 8, Size: 32, Value: 2971
  10.443851     Path: UPS.PowerSummary.iDeviceChemistry, Type: Feature, ReportID: 0x10, Offset: 0, Size: 8, Value: 4
  10.597714     Path: UPS.PowerSummary.PercentLoad, Type: Feature, ReportID: 0x07, Offset: 0, Size: 8, Value: 10
  10.597797     Path: UPS.PowerSummary.PresentStatus.ACPresent, Type: Feature, ReportID: 0x01, Offset: 0, Size: 8, Value: 1
  10.597847     Path: UPS.PowerSummary.PresentStatus.BelowRemainingCapacityLimit, Type: Feature, ReportID: 0x01, Offset: 8, Size: 8, Value: 0
  10.597897     Path: UPS.PowerSummary.PresentStatus.Charging, Type: Feature, ReportID: 0x01, Offset: 16, Size: 8, Value: 1
  10.597946     Path: UPS.PowerSummary.PresentStatus.Discharging, Type: Feature, ReportID: 0x01, Offset: 24, Size: 8, Value: 0
  10.597989     Path: UPS.PowerSummary.PresentStatus.Overload, Type: Feature, ReportID: 0x02, Offset: 16, Size: 8, Value: 0
  10.598033     Path: UPS.PowerSummary.PresentStatus.ShutdownImminent, Type: Feature, ReportID: 0x02, Offset: 24, Size: 8, Value: 0
  10.598050     find_nut_info: unknown info type: load.off.delay
  10.598061     find_nut_info: unknown info type: load.on.delay
  10.598071     find_nut_info: unknown info type: load.off.delay

Only tested on a Powerwalker VI 750T/HID

### CODE REVIEW

**Comment by tiagofreire-pt** [comment]
Could this be merged, please?

Thanks

**Comment by jimklimov** [comment]
@zykh @aquette @clepple : is there something blocking this PR from merging?

**Comment by clepple** [comment]
> is there something blocking this PR from merging? Does not seem like a large conflictey change...

@jimklimov I don't have hardware to test it, but as best I can tell from reading the code, mge-hid.c and liebert-hid.c conflict (both specify the USB ID `06da:ffff`), and I think the MGE/Eaton tables would match first. I am not sure how @gprints got the output shown above.

**Comment by gprints** [comment]
I'm simply running a 2.7.4 ups.conf specifying
driver = usbhid-ups
port = auto
It worked out of the box, I just wanted more data and a more precise battery voltage. I did not change anything in the USB part. If after 2.7.4 a conflict between mge-hid.c and liebert-hid.c arose, this must be due to some other patch.

**Pull request merged**
