### PR TITLE
drivers/nutdrv_qx.c: add support for Armac UPS (maybe richcomm)

### PR DESCRIPTION
**Pull request by blaa**
Based on Armac R/2000I/PSW, but should support other UPSes that work with
"PowerManagerII" software from Richcomm Technologies from around 2004-2005.

Closes https://github.com/networkupstools/nut/issues/1238

Tested to support querying, short and 10 minut tests.  UPS is currently 300km from me so I can't pull the plug to test status change though. I'm unsure about battery measurement - seems to return different values than richcomm software. Otherwise seems to work.

```
2348.670749     [D3] armac command Q1 response read: '(239.0 140.0 237.0 010 50.5 54.0 32.0 00001000'
2349.452441     [D1] upsdrv_updateinfo...
2349.452752     [D1] Quick update...
2350.667364     [D3] armac command Q1 response read: '(239.0 140.0 237.0 010 50.0 54.0 32.0 00001000'
2351.453304     [D1] upsdrv_updateinfo...
2351.453538     [D1] Quick update...
2352.674010     [D3] armac command Q1 response read: '(239.0 140.0 237.0 010 50.0 54.0 32.0 00001000'
2353.454108     [D1] upsdrv_updateinfo...
2353.454310     [D1] Quick update...
2354.670878     [D3] armac command Q1 response read: '(239.0 140.0 237.0 010 50.0 54.0 32.0 00001000'

# ./upsc armac
battery.charge: 100
battery.voltage: 54.00
battery.voltage.high: 52.00
battery.voltage.low: 41.60
battery.voltage.nominal: 48.0
device.type: ups
driver.name: nutdrv_qx
driver.parameter.nominal_cell_voltage: 13
driver.parameter.number_of_battery_cells: 4
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.productid: 1234
driver.parameter.subdriver: armac
driver.parameter.synchronous: no
driver.parameter.vendorid: 0925
driver.version: 2.7.4-3665-ga82b064a
driver.version.data: Megatec 0.06
driver.version.internal: 0.30
input.current.nominal: 14.0
input.frequency: 50.5
input.frequency.nominal: 50
input.voltage: 239.0
input.voltage.fault: 140.0
input.voltage.nominal: 220
output.voltage: 237.0
ups.beeper.status: disabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: Ver1.00
ups.load: 10
ups.productid: 1234
ups.status: OL
ups.temperature: 32.0
ups.type: offline / line interactive
ups.vendorid: 0925
```

### CODE REVIEW

**Comment by blaa** [comment]
I should probably update docs a bit. UPS list is either generated or should be updated manually, but I'm unsure.  I just went through https://github.com/networkupstools/nut/pull/1135/files and I it gives some basic ideas what to fix. Also, maybe CI will find something.

**Comment by jimklimov** [comment]
Good question about the naming. To me, at least after dealing with NUT codebase a lot, "richcomm" is a name I saw often, and "armac" possibly never yet. On another hand, I think we currently do not know whether this code supports all richcomm devices (and/or all those supported by existing richcomm_usb.c) - that is, if it may be named a replacement.

So weighing all the unknowns, I think this subdriver name can remain "armac" as a known compatible use-case. If wider community testing shows it is a viable replacement for stand-alone "richcomm" driver, it may get aliased later (if the parser for C-code table would tolerate that, or in the docs). Or at worst renamed as a "breaking change" for some future release... :\

**Comment by jimklimov** [comment]
Revised some cosmetic fixes (to align code style with other routines, and with what will land from libusb-1.0(+0.1) branches soon.

Also changed a few variable definitions to follow system headers (e.g. strlen and memset deal with size_t), and I think got a bug with your memset size argument (we want size of array, not of its one char element).

Will push the updated branch with some conflict resolution, shortly.

**Comment by jimklimov** [comment]
Weird, not sure why github closed this :\

**Comment by jimklimov** [comment]
I guess I mistyped the git-push :( Re-opened from my branch as #1250

**Comment by Achy7** [comment]
on hassio that i have 2.7.4 how can update ?

**Comment by jimklimov** [comment]
@Achy7 : this question was not about the PR here, but a general one for HA and NUT integration, to get a wholesale new NUT built. See some suggestions in Wiki.

**Pull request closed without merging**
