### PR TITLE
Fix docs RO resources and enable cables HTML docs

### PR DESCRIPTION
**Pull request by jimklimov**
Picking up from #425 by @stanislav-brabec

### CODE REVIEW

**Comment by clepple** [comment]
Looks good to me.

(sorry for the delay, not sure how long this comment has been sitting in the browser window)

**Comment by jimklimov** [comment]
Thanks

**Comment by clepple** [comment]
So I'm not sure if this is specifically due to this merge, but I am seeing an error related to `FAQ.html` here: http://buildbot.networkupstools.org/public/nut/builders/Debian-website/builds/75/steps/shell/logs/stdio

Not sure if we use FAQ.chunked anyway? It's just a single page on the website.

It will probably mean more Travis builds, and slightly exciting merge semantics due to submodules, but I should probably do more testing on branches with the nut-to-website integration.

**Comment by clepple** [comment]
@jimklimov not sure if you get notifications on closed PRs, but in addition to the previous comment, the recent [nut-website Travis failure](https://travis-ci.org/networkupstools/nut-website/jobs/274439699) seems orthogonal to this issue.

**Comment by jimklimov** [comment]
I'll take a look... it seems that website issue is on Travis side - fails to write during pycparser installation. Probably needs a sudo option in travis.yml.

Thanks for catching these, I'll take a deeper look.

**Pull request merged**
