### PR TITLE
Read physical outlet type in Eaton Marlin MiB

### PR DESCRIPTION
**Pull request by vyskocilm**

### CODE REVIEW

**Comment by aquette** [comment]
Thanks Michal!
Prior to approving this PR, I'd like to check other implementations (I got Raritan underhand), in order to standardize the values in NUT

**Comment by aquette** [comment]
List of values from Eaton PDU:
		unknown (0),
		iecC13 (1),
		iecC19 (2),
		uk (10),
		french (11),
		schuko (12),
		nema515 (20),
		nema51520 (21),
		nema520 (22),
		nemaL520 (23),
		nemaL530 (24),
		nema615 (25),
		nema620 (26),
		nemaL620 (27),
		nemaL630 (28),
		nemaL715 (29),
		rf203p277 (30)


List of values from Raritan PDU:

		receptacleOTHER(-1),
		receptacleNONE(0),
		receptacleBS1363(1), 
		receptacle56P532(3), 
		receptacleCS8364C(4), 
		receptacleIEC320C13(5), 
		receptacleIEC320C19(6), 
		receptacleIEC603093WIRE250V16A(7), 
		receptacleIEC603093WIRE250V20A(8), 
		receptacleIEC603093WIRE250V30A(9), 
		receptacleIEC603093WIRE250V32A(10), 
		receptacleIEC603093WIRE250V60A(11), 
		receptacleIEC603093WIRE250V63A(12), 
		receptacleIEC603093WIRE250V100A(13), 
		receptacleIEC603093WIRE250V125A(14), 
		receptacleIEC603094WIRE250V20A(15), 
		receptacleIEC603094WIRE250V30A(16), 
		receptacleIEC603094WIRE250V60A(17), 
		receptacleIEC603094WIRE250V100A(18), 
		receptacleIEC603095WIRE208V20A(23), 
		receptacleIEC603095WIRE208V30A(24), 
		receptacleIEC603095WIRE208V60A(25), 
		receptacleIEC603095WIRE208V100A(26), 
		receptacleIEC603095WIRE415V16A(27), 
		receptacleIEC603095WIRE415V32A(28), 
		receptacleIEC603095WIRE415V63A(29), 
		receptacleIEC603095WIRE415V125A(30), 
		receptacleIEC603095WIRE480V20A(31),
		receptacleIEC603095WIRE480V30A(32),
		receptacleIEC603095WIRE480V60A(33),
		receptacleIEC603095WIRE480V100A(34),
		receptacleNEMA515R(35), 
		receptacleNEMAL515R(36), 
		receptacleNEMA520R(37), 
		receptacleNEMAL520R(38), 
		receptacleNEMAL530R(39), 
		receptacleNEMAL615R(40), 
		receptacleNEMAL620R(41), 
		receptacleNEMAL630R(42), 
		receptacleNEMAL1520R(43), 
		receptacleNEMAL1530R(44), 
		receptacleNEMAL2120RP(45), 
		receptacleNEMAL2130R(46),
		receptacleSCHUKOTYPEE(47),
		receptacleSCHUKOTYPEF(48)

**Comment by vyskocilm** [comment]
The Raritan usually encodes more information than Eaton. However we can map
 * unknown, receptacleOTHER and receptacleNONE to unknown
 * uk receptacleBS1363 to bs1363 (uk)
 * iecC13, receptacleIEC320C13 can be iecC13 or iecC320C13 (the same for 19)

For the rest I would not do any bigger standartization, just improve readability of Raritan mapping (receptacleSCHUKOTYPEE -> shuko (type F))

**Comment by balooloo** [comment]
I think we should not interpret unkown, other and none as the same value as they really represent different semantic.
* Other is a type we do not encode
* None is a socket that is not physically available (for any reason)
* Unknwon is we cannot retrieve the information.

**Comment by vyskocilm** [comment]
I don't think I can help on this PR anymore - closing it.

**Pull request merged**
