### PR TITLE
Fix builds against older GCC (no C++11 in the system)

### PR DESCRIPTION
**Pull request by jimklimov**
Hopefully would rectify http://buildbot.networkupstools.org/public/nut/builders/OpenBSD-x64/builds

CC : @boricj

### CODE REVIEW

**Comment by jimklimov** [comment]
Updated the `pull_668_cxx11` branch with the updated commit for buildbot to pick it up, but now it replies HTTP 503... :\

**Comment by clepple** [comment]
> but now it replies HTTP 503... :\

One of these days I should get that proxy to start on its own :)

**Comment by jimklimov** [comment]
Thanks for this and other recent reviews :)

**Comment by clepple** [comment]
No problem--sorry I'm terribly behind on this. New batteries are coming for my MGE UPS, though, so the network is finally getting put back together.

**Pull request merged**
