### PR TITLE
docs/acknowledgements.txt: revise the last paragraph for listing corporate contributors

### PR DESCRIPTION
**Pull request by jimklimov**
Another potential bike-shedding moment, so posting the small change as a separate PR.

### CODE REVIEW

**Comment by jimklimov** [comment]
One point to consider going forward - how much we prefer the mailing list ("send us some mail") vs. raising issues and PRs on GitHub? I'd rather drop the suggestion to "send mail" so it is less likely we'd miss the message.

**Review by aquette — APPROVED** [review]

**Comment by aquette** [comment]
Also something that was on my todo:
Going GH is better imo nowadays

**Comment by clepple** [comment]
I think GitHub is certainly more efficient for code review of larger changes, but consider the user who is not a developer: below a certain size threshold, it is not worth their time to read the TOS and sign up for GitHub (it would be a little different if this were a self-hosted GitLab instance maybe, but I’m not necessarily suggesting that would be better for us). I’ve filed issues for things brought up on the mailing list in the past, and have no problem continuing to do so (time permitting). After all, if I need to research a NUT issue, I’m going to go to my email archive first, not search GitHub.

**Review by clepple — APPROVED** [review]

**Comment by jimklimov** [comment]
Ok, keeping the dual mail-github wording here then :)

**Pull request merged**
