### PR TITLE
tripplite_usb.c Enhanced Device Identification in the tripplite_usb Driver for Tripp Lite USB UPSes

### PR DESCRIPTION
**Pull request by sapireli**
driver matching by ups.id since serial number isn't exposed on devices

for #2075

follows up from #2074 and #2093

### CODE REVIEW

**Comment by jimklimov** [comment]
you don't have to open new PRs for each push. Keep iterating in same branch
:)

**Comment by maximilanna** [comment]
Sorry! :) i'm a monkey

**Comment by maximilanna** [comment]
The newly committed code in the tripplite_usb.c file includes several modifications to enhance the functionality of the driver for Tripp Lite USB UPSes. Here is a summary of the modifications made:

1. Added UPS ID (upsid) Support: The code now includes support for matching and uniquely identifying UPS devices using the UPS ID (upsid). This allows for precise identification of UPS devices when multiple devices are connected. The upsid configuration option has been added, which accepts a regular expression to match the UPS ID string.

This was done by adding a new function called match_by_upsid, that reads the upsid from the config file, then reads the upsid from the device, and checks if they match. This function is now passed to the comm_driver matcher on first connect and reconnects.

Added the upsid to the upsdrv_makevartable function so it is read and stored from the config file.
 
2. Updated Documentation: The  tripllite_usb driver documentation has been updated to reflect the new functionality. The "EXTRA ARGUMENTS" section now includes information about the upsid configuration option, explaining how it can be used to identify and select a specific UPS by its unique UPS ID.
 
Huge thank you to @jimklimov for pointing me in the right direction and hand holding.

**Comment by jimklimov** [comment]
Oh, nice, I've fixed CI and now it has complaints again, and different toolkits, old and young, agree on some issues :)

* clang-16:
````
tripplite_usb.c:327:20: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int match_by_unitid() 
                   ^
                    void
tripplite_usb.c:327:5: error: no previous prototype for function 'match_by_unitid' [-Werror,-Wmissing-prototypes]
int match_by_unitid() 
    ^
tripplite_usb.c:327:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
int match_by_unitid() 
^
static 
tripplite_usb.c:335:9: error: variable 'config_unit_id' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    if (value != NULL) {
        ^~~~~~~~~~~~~
tripplite_usb.c:350:9: note: uninitialized use occurs here
    if (config_unit_id == unit_id) {
        ^~~~~~~~~~~~~~
tripplite_usb.c:335:5: note: remove the 'if' if its condition is always true
    if (value != NULL) {
    ^~~~~~~~~~~~~~~~~~~
tripplite_usb.c:330:23: note: initialize the variable 'config_unit_id' to silence this warning
    int config_unit_id;
                      ^
                       = 0
tripplite_usb.c:374:65: error: incompatible function pointer types passing 'int ()' to parameter of type 'int (*)(usb_dev_handle *, USBDevice_t *, usb_ctrl_charbuf, usb_ctrl_charbufsize)' (aka 'int (*)(struct libusb_device_handle *, struct USBDevice_s *, unsigned char *, unsigned short)') [-Werror,-Wincompatible-function-pointer-types-strict]
        ret = comm_driver->open_dev(&udev, &curDevice, reopen_matcher, match_by_unitid);
                                                                       ^~~~~~~~~~~~~~~
tripplite_usb.c:1645:62: error: incompatible function pointer types passing 'int ()' to parameter of type 'int (*)(usb_dev_handle *, USBDevice_t *, usb_ctrl_charbuf, usb_ctrl_charbufsize)' (aka 'int (*)(struct libusb_device_handle *, struct USBDevice_s *, unsigned char *, unsigned short)') [-Werror,-Wincompatible-function-pointer-types-strict]
        r = comm_driver->open_dev(&udev, &curDevice, regex_matcher, match_by_unitid);
                                                                    ^~~~~~~~~~~~~~~
5 errors generated.
make[1]: *** [Makefile:1965: tripplite_usb.o] Error 1
make[1]: Target 'all' not remade because of errors.
````

* clang-3.4:
````
tripplite_usb.c:327:5: error: no previous prototype for function 'match_by_unitid' [-Werror,-Wmissing-prototypes]
int match_by_unitid() 
    ^
tripplite_usb.c:335:9: error: variable 'config_unit_id' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    if (value != NULL) {
        ^~~~~~~~~~~~~
tripplite_usb.c:350:9: note: uninitialized use occurs here
    if (config_unit_id == unit_id) {
        ^~~~~~~~~~~~~~
tripplite_usb.c:335:5: note: remove the 'if' if its condition is always true
    if (value != NULL) {
    ^~~~~~~~~~~~~~~~~~~
tripplite_usb.c:330:23: note: initialize the variable 'config_unit_id' to silence this warning
    int config_unit_id;
                      ^
                       = 0
tripplite_usb.c:374:65: error: incompatible pointer types passing 'int ()' to parameter of type 'int (*)(usb_dev_handle *, USBDevice_t *, usb_ctrl_charbuf, usb_ctrl_charbufsize)' [-Werror,-Wincompatible-pointer-types]
        ret = comm_driver->open_dev(&udev, &curDevice, reopen_matcher, match_by_unitid);
                                                                       ^~~~~~~~~~~~~~~
tripplite_usb.c:1645:62: error: incompatible pointer types passing 'int ()' to parameter of type 'int (*)(usb_dev_handle *, USBDevice_t *, usb_ctrl_charbuf, usb_ctrl_charbufsize)' [-Werror,-Wincompatible-pointer-types]
        r = comm_driver->open_dev(&udev, &curDevice, regex_matcher, match_by_unitid);
                                                                    ^~~~~~~~~~~~~~~
4 errors generated.
make[1]: *** [tripplite_usb.o] Error 1
make[1]: Target `all' not remade because of errors.
Making all in tools
````

* gcc-4.8:
````
../../drivers/tripplite_usb.c: In function 'reconnect_ups':
../../drivers/tripplite_usb.c:374:2: error: passing argument 4 of 'comm_driver->open_dev' from incompatible pointer type [-Werror]
  ret = comm_driver->open_dev(&udev, &curDevice, reopen_matcher, match_by_unitid);
  ^
../../drivers/tripplite_usb.c:374:2: note: expected 'int (*)(struct usb_dev_handle *, struct USBDevice_t *, unsigned char *, usb_ctrl_charbufsize)' but argument is of type 'int (*)()'
../../drivers/tripplite_usb.c: In function 'upsdrv_initups':
../../drivers/tripplite_usb.c:1645:2: error: passing argument 4 of 'comm_driver->open_dev' from incompatible pointer type [-Werror]
  r = comm_driver->open_dev(&udev, &curDevice, regex_matcher, match_by_unitid);
  ^
../../drivers/tripplite_usb.c:1645:2: note: expected 'int (*)(struct usb_dev_handle *, struct USBDevice_t *, unsigned char *, usb_ctrl_charbufsize)' but argument is of type 'int (*)()'
../../drivers/tripplite_usb.c: At top level:
cc1: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1: error: unrecognized command line option "-Wno-reserved-identifier" [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [tripplite_usb.o] Error 1
make[1]: Target `all' not remade because of errors.
````

**Comment by jimklimov** [comment]
Thanks for updating. Not sure if it will come up, but if some method args are not really used in it, add `NUT_UNUSED_VARIABLE(name);` after variable declarations on top of method code.

**Comment by jimklimov** [comment]
Added a few fixes (one apparent typo near contributor names, others mostly coding style)

**Comment by jimklimov** [comment]
Restarted as #2102

**Pull request closed without merging**
