### PR TITLE
Update upsmon ALARM support and related themes from issue #415

### PR DESCRIPTION
**Pull request by jimklimov**
Closes: #415
Follow-up to: #2658
Touches on: #2708

### CODE REVIEW

**Comment by jimklimov** [comment]
NOTE: This PR currently stops short of actually handling the notifications, as we would need some sort of `Map<String, Boolean>` to track that a non-standard token was raised once and remains raised continuously (otherwise it would notify about it every cycle).

Probably this can be done with dstate/sstate and a catch-all method similar to `ups_is_cal` et al (accepting the token as another parameter, and not caring about it beyond notification).

**Review by desertwitch — APPROVED** [review]
LGTM

**Comment by jimklimov** [comment]
Updated with more comprehensive `upsmon` support for "ALARM" (to report `ups.alarm` contents if the formatting string has two `%s` placeholders), and newly introduced older discussed "OTHER" to report any *changes* about `ups.status` tokens not known to `upsmon`.

The napkin logic makes sense to me and compiles, but was not tested - that would be most welcome :D

**Comment by jimklimov** [comment]
Verified with `make check-NIT-sandbox-devel` and modified generated `dummy.seq` to include alarm bits:
````
ups.status: OB
TIMER 5
ups.status: OL
TIMER 5
ups.status: ALARM OL BOGUS
ups.alarm: Test bug!
TIMER 2
````

Console messages:
````
UPS dummy@localhost:12345 on battery
UPS dummy@localhost:12345 on line power
UPS dummy@localhost:12345: one or more active alarms: [Test bug!]
UPS dummy@localhost:12345: has at least one unclassified status token: [BOGUS]
UPS dummy@localhost:12345 is no longer in an alarm state (no active alarms)
UPS dummy@localhost:12345 on battery
UPS dummy@localhost:12345 has no unclassified status tokens anymore
````

Using `notifyme-debug` as the handler got:
````
...
Thu Dec  5 20:10:29 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        ONBATT  [dummy@localhost:12345]:      UPS dummy@localhost:12345 on battery    (1 tokens)
Thu Dec  5 20:10:39 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        ONLINE  [dummy@localhost:12345]:      UPS dummy@localhost:12345 on line power (1 tokens)
Thu Dec  5 20:10:44 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        ALARM   [dummy@localhost:12345]:      UPS dummy@localhost:12345: one or more active alarms: [Test bug!]       (1 tokens)
Thu Dec  5 20:10:44 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        OTHER   [dummy@localhost:12345]:      UPS dummy@localhost:12345: has at least one unclassified status token: [BOGUS]  (1 tokens)
Thu Dec  5 20:10:49 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        ONBATT  [dummy@localhost:12345]:      UPS dummy@localhost:12345 on battery    (1 tokens)
Thu Dec  5 20:10:49 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        NOTALARM        [dummy@localhost:12345]:      UPS dummy@localhost:12345 is no longer in an alarm state (no active alarms)     (1 tokens)
Thu Dec  5 20:10:49 UTC 2024    [uid=1000(jim) gid=1000(jim) groups=1000(jim)]        NOTOTHER        [dummy@localhost:12345]:      UPS dummy@localhost:12345 has no unclassified status tokens anymore     (1 tokens)
...
````

It seems to lock up afterwards though, investigating.

**Comment by jimklimov** [comment]
Had some fun with `valgrind` to make sure these alert loops do not leak memory...

**Pull request merged**
