### PR TITLE
upsmon: fix discrepancies between linestate & status flags resulting in critical UPS

### LINKED ISSUE #2126: Network loss as NUT slave triggers instant FSD despite UPS last seen OL
There's an FSD issue with changes introduced by https://github.com/networkupstools/nut/commit/2647f026f7f0c856926da67cec845a09bed2a5d1 when NUT is acting as a slave (using just `upsmon`).

Despite the master UPS last being in an `OL` state, even a minor connectivity hickup triggers an instant UPS critical resulting in FSD (due to minSupplies being depleted).

This can be reproduced by setting up NUT as a slave (connected to a NUT master in state `OL`) and unplugging the ethernet cord long enough (~10-20s) for NUT to register the connection loss. UPS last remembered as `OL` should no go critical in such a situation but - with the current build from master - unfortunately right now do go critical and result in system shutdowns.

It seems the NUT slave's `upsmon` doesn't set `ups->linestate = 1;`  despite the NUT master seen as `OL`, resulting in UPS critical (due to `ups->linestate = 0;` + nocomms)  and minSupplies being depleted due to the critical UPS.

```
Oct 23 12:18:03 Tower upsmon[13442]: Startup successful
(pulling ethernet cord here)
Oct 23 12:18:23 Tower upsmon[13443]: Poll UPS [ups@192.168.0.15] failed - Server disconnected
Oct 23 12:18:23 Tower upsmon[13443]: Communications with UPS ups@192.168.0.15 lost
Oct 23 12:18:23 Tower upsmon[13443]: UPS [ups@192.168.0.15] was last known to be not fully online and currently is not communicating, assuming dead
Oct 23 12:18:23 Tower upsmon[13443]: Executing automatic power-fail shutdown
Oct 23 12:18:23 Tower upsmon[13443]: Auto logout and shutdown proceeding
```

There is no such issue when running in standalone/netserver mode with e.g. the SNMP driver and pulling the ethernet cord.

### PR DESCRIPTION
**Pull request by desertwitch**
fixes #2126 

previously OL devices now no longer go critical in nocomms situations (as intended)
previously not-OL devices still go critical in nocomms situations (as intended)

tested the following situations:
- NUT as master with SNMP driver, UPS last seen as OL => not critical on comm-loss (as intended, works)
- NUT as master with SNMP driver, UPS last seen as OB => critical on comm-loss (as intended, works)
- NUT as slave with NUT master last seen as OL => not critical on comm-loss (as intended, works)
- NUT as slave with NUT master last seen as OB => critical on comm-loss (as intended, works)

input welcome (first code-wise contribution to the project)

### CODE REVIEW

**Comment by jimklimov** [comment]
Interesting... the analysis and proposed change make sense, but this code-path exists for two decades since initial git import by @aquette and probably predates that (in SVN and tarball eras).

Could you please double-check if NUT v2.8.0 or 2.7.4 releases (mis-)behave similarly? I'm sure that over this time someone would have noticed - that is, if it's an old issue and not a new bug introduced by recent attempts to fix the OFF/BYPASS/CAL state handling.

**Comment by desertwitch** [comment]
It's a new bug introduced by https://github.com/networkupstools/nut/commit/2647f026f7f0c856926da67cec845a09bed2a5d1. This is how I noticed it to begin with, as users started complaining after switching from a build from around 2-3 weeks ago to the current master build. The reason it now occurs is that we previously didn't consider a UPS with commstate=0 && linestate=0 as critical. linestate seems to not habe been evaluated to determine UPS criticality before that commit at all, hence nulling it had no effect as the ONLINE flag was not cleared and remained present from before the NOCOMMS - resulting in the behavior we wanted. Now that we're evaluating linestate we're running into this problem. 

Another way around this (as opposed to my PR) would be to evaluate the UPS flags instead of linestate in combination with commstate to determine UPS criticality, as those are not cleared in a NOCOMMS situation. So commstate=0 && !ST_ONLINE instead of commstate=0 && linestate=0. If you'd prefer to keep nulling the linestate to clean up connection drop, I can adapt the UPS criticality function for flags instead?

**Comment by desertwitch** [comment]
Just tested again and doesn't occur on 2.8.0 stable - NOCOMMS doesn't (ever) UPS criticality on those.

This would be the other way I've mentioned above (as opposed to my PR), but I think this would basically be a "workaround" for keeping a falsified (or prematurely/falsely assumed) linestate variable around (and accounting for a ST_ONLINE flag while the linestate is incorrectly 0):
https://github.com/networkupstools/nut/blob/2647f026f7f0c856926da67cec845a09bed2a5d1/clients/upsmon.c#L1041-L1073

```
if (ups->commstate == 0 && !flag_isset(ups->status, ST_ONLINE)) {
		if (flag_isset(ups->status, ST_CAL)) {
			upslogx(LOG_WARNING,
				"UPS [%s] was last known to be calibrating "
				"and currently is not communicating, assuming dead",
				ups->sys);
			return 1;
		}

		if (ups->bypassstate == 1
		|| flag_isset(ups->status, ST_BYPASS)) {
			upslogx(LOG_WARNING,
				"UPS [%s] was last known to be on BYPASS "
				"and currently is not communicating, assuming dead",
				ups->sys);
			return 1;
		}

		if (ups->offstate == 1
		|| (offdurationtime >= 0 && flag_isset(ups->status, ST_OFF))) {
			upslogx(LOG_WARNING,
				"UPS [%s] was last known to be (administratively) OFF "
				"and currently is not communicating, assuming dead",
				ups->sys);
			return 1;
		}

		upslogx(LOG_WARNING,
			"UPS [%s] was last known to be not fully online "
			"and currently is not communicating, assuming dead",
			ups->sys);
		return 1;
	}

```

This above change we could - of course - also use in conjunction with the PR's proposed change. This way we would rectify the prematurely assumed line state and also keep the UPS criticality function consistent on using flags rather than the state variables to evaluate UPS criticality.

Probably also here then:
https://github.com/networkupstools/nut/blob/2647f026f7f0c856926da67cec845a09bed2a5d1/clients/upsmon.c#L1076
`if (flag_isset(ups->status, ST_OFF) && offdurationtime >= 0 && !flag_isset(ups->status, ST_ONLINE)) {`

**Comment by jimklimov** [comment]
Answering to one of the earlier posts above, regarding the `drop_connection()` method per se - I think it intentionally clears all known state about the UPS which we plan to forget about, and in this role makes sense to remain that way. It may be argued if we want (all of) this method called when a connection to the data server times out.

I also remember from the docs that were around forever that during a critical power situation a loss of connection between a (slave?) `upsmon` and its data server is treated as a reason to shut down - assuming that some other UPS or wall power that fed the switches has died. Maybe I forgot too much of other context, such as being in FSD mode already (IIRC there is a provision in the *primary* upsmon that waits for secondaries to log out cleanly before it goes on to shut down its host and the UPS - and goes quicker about it if the secondaries just go offline/timeout)...

**Comment by jimklimov** [comment]
I'll read the rest of your answers tomorrow, got just a short online time tonight.

**Comment by desertwitch** [comment]
> Answering to one of the earlier posts above, regarding the `drop_connection()` method per se - I think it intentionally clears all known state about the UPS which we plan to forget about, and in this role makes sense to remain that way. It may be argued if we want (all of) this method called when a connection to the data server times out.

Yes, but at present that's not what the function is doing. It's only clearing the linestate but not the flags and creating a discrepancy between the two in the process. And as the second part of your answer (below) states correctly a connection loss should be treated as a shutdown reason, but only in a critical power situation. By nulling the linestate here we're essentially creating such a critical power situation always, even if the UPS was online before no-comms.

> I also remember from the docs that were around forever that during a critical power situation a loss of connection between a (slave?) `upsmon` and its data server is treated as a reason to shut down - assuming that some other UPS or wall power that fed the switches has died. Maybe I forgot too much of other context, such as being in FSD mode already (IIRC there is a provision in the *primary* upsmon that waits for secondaries to log out cleanly before it goes on to shut down its host and the UPS - and goes quicker about it if the secondaries just go offline/timeout)...

Exactly and this PR allows for this to happen instead of always assuming a power loss situation despite there not being one.

**Comment by desertwitch** [comment]
2.8.0 stable log (no depletion of minSupplies as UPS criticality is not raised due to preserved flags [correctly ST_ONLINE] and not evaluating linestate [wrongly 0, but no effect since no evaluation] in UPS criticality evaluation function):
```
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D1] Logged into UPS ups@192.168.0.15
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D2] pollups: ups@192.168.0.15
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D2] parse_status: [OL]
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D3] parsing: [OL]
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D3] ups_on_line: ups@192.168.0.15 (first time)
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D3] Current power value: 1
Oct 23 22:07:05 TowerOLD  upsmon[3788]: [D3] Minimum power value: 1
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D2] pollups: ups@192.168.0.15
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D2] parse_status: [OL]
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D3] parsing: [OL]
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D4] ups_on_line: ups@192.168.0.15 (no change)
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D3] Current power value: 1
Oct 23 22:07:10 TowerOLD  upsmon[3788]: [D3] Minimum power value: 1
Oct 23 22:07:15 TowerOLD  upsmon[3788]: [D2] pollups: ups@192.168.0.15
Oct 23 22:07:15 TowerOLD  upsmon[3788]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 22:07:20 TowerOLD  upsmon[3788]: Poll UPS [ups@192.168.0.15] failed - Server disconnected
Oct 23 22:07:20 TowerOLD  upsmon[3788]: [D2] do_notify: ntype 0x0005 (COMMBAD)
Oct 23 22:07:20 TowerOLD  upsmon[3788]: Communications with UPS ups@192.168.0.15 lost
Oct 23 22:07:20 TowerOLD  upsmon[3788]: [D2] Dropping connection to UPS [ups@192.168.0.15]
Oct 23 22:07:20 TowerOLD  upsmon[3788]: [D3] Current power value: 1
Oct 23 22:07:20 TowerOLD  upsmon[3788]: [D3] Minimum power value: 1
Oct 23 22:07:25 TowerOLD  upsmon[3788]: [D1] Trying to connect to UPS [ups@192.168.0.15]
Oct 23 22:07:57 TowerOLD  upsmon[3788]: [D1] Logged into UPS ups@192.168.0.15
Oct 23 22:07:57 TowerOLD  upsmon[3788]: [D2] pollups: ups@192.168.0.15
Oct 23 22:07:57 TowerOLD  upsmon[3788]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 22:07:57 TowerOLD  upsmon[3788]: [D2] parse_status: [OL]
Oct 23 22:07:57 TowerOLD  upsmon[3788]: [D2] do_notify: ntype 0x0004 (COMMOK)
Oct 23 22:07:57 TowerOLD  upsmon[3788]: Communications with UPS ups@192.168.0.15 established
```

current master log (depletion of minSupplies as UPS criticality is raised due to the changes in https://github.com/networkupstools/nut/commit/2647f026f7f0c856926da67cec845a09bed2a5d1 now evaluating both linestate [wrongly 0, now having an effect because of evaluation - see commit changes] and flags [correctly ST_ONLINE])
```
Oct 23 13:01:40 Tower upsmon[23466]: [D1] Trying to connect to UPS [ups@192.168.0.15]
Oct 23 13:01:40 Tower upsmon[23466]: [D1] Logged into UPS ups@192.168.0.15
Oct 23 13:01:40 Tower upsmon[23466]: [D2] pollups: ups@192.168.0.15
Oct 23 13:01:40 Tower upsmon[23466]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 13:01:40 Tower upsmon[23466]: [D2] parse_status: [OL]
Oct 23 13:01:40 Tower upsmon[23466]: [D3] parsing: [OL]
Oct 23 13:01:40 Tower upsmon[23466]: [D3] ups_on_line: ups@192.168.0.15 (first time)
Oct 23 13:01:40 Tower upsmon[23466]: [D3] Current power value: 1
Oct 23 13:01:40 Tower upsmon[23466]: [D3] Minimum power value: 0
Oct 23 13:01:45 Tower upsmon[23466]: [D2] pollups: ups@192.168.0.15
Oct 23 13:01:45 Tower upsmon[23466]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 13:01:45 Tower upsmon[23466]: [D2] parse_status: [OL]
Oct 23 13:01:45 Tower upsmon[23466]: [D3] parsing: [OL]
Oct 23 13:01:45 Tower upsmon[23466]: [D4] ups_on_line: ups@192.168.0.15 (no change)
Oct 23 13:01:45 Tower upsmon[23466]: [D3] Current power value: 1
Oct 23 13:01:45 Tower upsmon[23466]: [D3] Minimum power value: 0
Oct 23 13:01:50 Tower upsmon[23466]: [D2] pollups: ups@192.168.0.15
Oct 23 13:01:50 Tower upsmon[23466]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 13:01:50 Tower upsmon[23466]: [D2] parse_status: [OL]
Oct 23 13:01:50 Tower upsmon[23466]: [D3] parsing: [OL]
Oct 23 13:01:50 Tower upsmon[23466]: [D4] ups_on_line: ups@192.168.0.15 (no change)
Oct 23 13:01:50 Tower upsmon[23466]: [D3] Current power value: 1
Oct 23 13:01:50 Tower upsmon[23466]: [D3] Minimum power value: 0
Oct 23 13:01:55 Tower upsmon[23466]: [D2] pollups: ups@192.168.0.15
Oct 23 13:01:55 Tower upsmon[23466]: [D3] get_var: ups@192.168.0.15 / status
Oct 23 13:02:00 Tower upsmon[23466]: [D3] pollups: Poll UPS [ups@192.168.0.15] after getvar(status) failed: upserror=38
Oct 23 13:02:00 Tower upsmon[23466]: Poll UPS [ups@192.168.0.15] failed - Server disconnected
Oct 23 13:02:00 Tower upsmon[23466]: [D2] do_notify: ntype 0x0005 (COMMBAD)
Oct 23 13:02:00 Tower upsmon[23466]: [D6] notify: sending notification for [ups@192.168.0.15]: type COMMBAD with flags 0x0006: Communications with UPS ups@192.168.0.15 lost
Oct 23 13:02:00 Tower upsmon[23466]: [D6] notify: NOTIFY_SYSLOG (as LOG_NOTICE)
Oct 23 13:02:00 Tower upsmon[23466]: Communications with UPS ups@192.168.0.15 lost
Oct 23 13:02:00 Tower upsmon[23466]: [D6] notify (parent): forked a child to notify via subprocesses
Oct 23 13:02:00 Tower upsmon[23466]: [D2] Dropping connection to UPS [ups@192.168.0.15]
Oct 23 13:02:00 Tower upsmon[23466]: UPS [ups@192.168.0.15] was last known to be not fully online and currently is not communicating, assuming dead
Oct 23 13:02:00 Tower upsmon[23466]: [D1] Critical UPS: ups@192.168.0.15
Oct 23 13:02:00 Tower upsmon[23466]: [D3] Current power value: 0
Oct 23 13:02:00 Tower upsmon[23466]: [D3] Minimum power value: 0
```

**Comment by jimklimov** [comment]
Ok, re-read now and seems to make sense - well :)

Wondering if we should produce some extra report (debug log? notification?) like "Conn lost, last known state flags were: X Y Z"? WDYT - would that be helpful?

**Comment by desertwitch** [comment]
> Ok, re-read now and seems to make sense - well :)
> 
> Wondering if we should produce some extra report (debug log? notification?) like "Conn lost, last known state flags were: X Y Z" (maybe with a pinch of their resulting criticality)? WDYT - would that be helpful?

First of all thanks for taking the time to read my (admitted longer than initially intended) ramblings. 😆 

Yes, I think the last seen status makes sense in `drop_connection` as a debug message. The UPS going critical already raises notifications as to why it's now critical, but putting the last remembered status as an additional (debug) information to better understand which previous status triggers the UPS criticality (and what the UPS was doing before) would indeed be helpful.

I'll attempt to implement this and push a commit to the PR once I'm done.

**Comment by desertwitch** [comment]
Not sure if this is sufficient, might be better to enumerate and print all remembered status flags in the debug message instead of just the linestate (but not sure how, so feel free to change around).

**Comment by jimklimov** [comment]
For `ups.status` I think there's a bit of crossroads here:
* current info (not necessarily parsed yet): `if (get_var(ups, "status", status, sizeof(status)) == 0) {...}` like in `pollups()`
* stringify back the `upsmon` info model from the `ups` structure - seems more relevant as it is the info it acts on eventually

**Comment by desertwitch** [comment]
Have another idea that evaluates only the information we act on, introduces a sanity check and saves compute time.

Let's see... going to be a few minutes to adapt and test it...

**Comment by desertwitch** [comment]
I think this way lays a nice foundation using the same terminology as used later to raise UPS criticality, while also only evaluating the variables we're effectively basing/deciding the UPS criticality on and saving us complex enumerations of status flags that are irrelevant to the code-path deciding on the UPS criticality. What do you think?

**Comment by jimklimov** [comment]
Seems better :) Still thinking whether OFF/BYPASS (whether active variables subject to timeouts, or ST_... flags) should be reported here if they later can factor in an FSD decision.

**Comment by desertwitch** [comment]
Hmm, not 100% sold on that (yet), because a lot can factor into an FSD decision when `ups->commstate == 0` (also `CAL` actually, next to `BYPASS` and `OFF`). However the one single necessary precursor for all of that to even be considered for UPS criticality is `ups->linestate == 0` or `!flag_isset(ups->status, ST_ONLINE)` respectively. So I think it'd make more sense to print only this as the last remembered state on `connection_drop`, with the other might-or-might-not-get-critical flags already raising their own debug messages first in their respective occurence functions (when non-critical) and second also in the UPS criticality evaluation function itself (when critical).

**Comment by jimklimov** [comment]
Ok, leaving it at "less is more" for now then :) If someone complains later, we can extend it later.

**Comment by desertwitch** [comment]
> Ok, leaving it at "less is more" for now then :) If someone complains later, we can extend it later.

No, you're actually right, I had a knot in my head there.
linestate == 0 is not a necessary precursor for FSD when on CAL, BYPASS, OFF & commstate == 0

I'll integrate this, as you're right that they warrant debug messages in a comm-loss scenario (even if the line is up)

**Comment by jimklimov** [comment]
Heh, so "we" complained later, and it did not take that long :)

**Comment by jimklimov** [comment]
Heh, rebuild running (for same commit, had a hiccup on CI farm) - but old failure messages are still in place :}

**Comment by desertwitch** [comment]
> Heh, rebuild running (for same commit, had a hiccup on CI farm) - but old failure messages are still in place :}

Was it a code-related failure or due to the CI hiccup?

**Comment by jimklimov** [comment]
CI itself, I think. VM disk timeouts under stress (Fosshost is dead for a year, but the VMs still run).

**Comment by desertwitch** [comment]
> CI itself, I think. VM disk timeouts under stress (Fosshost is dead for a year, but the VMs still run).

Can close and reopen PR if that'd help clear the erroneous checks, let me know.

**Comment by jimklimov** [comment]
Nay, just will ignore them as we know the cause :) Notifications are tied to commit-hash and an assigned "context", and perhaps the pipeline should start by either clearing the contexts it expects to post later if it can predict them, or somehow list all statuses and clear those it owns... or leave it be until it becomes too annoying (notification rework is a work in progress of the past days).

**Comment by desertwitch** [comment]
Was since able to test this with another affected user and our changes in the PR resolve the issue for them as well.

**Pull request merged**
