### PR TITLE
Readme broken url

### PR DESCRIPTION
**Pull request by prasket**
Noticed a broken link in README when I was trying to research NUT for my use case so I thought I would fix it. I also reworded just a bit as it looked odd just having [online]. at the end after the hyperlink.

### CODE REVIEW

**Comment by clepple** [comment]
Hmm, I don't remember Github rendering those links as HTML before.

The problem is that the README is also parsed as AsciiDoc, and is included as part of the user manual:

https://networkupstools.org/docs/user-manual.chunked/ar01s02.html#_hardware_compatibility_list

(Unlike Markdown, bare URLs are not automatically turned into hyperlinks with `asciidoc`.)

**Comment by jimklimov** [comment]
I believe one way around this would be to `git mv README README.asciidoc` (Github honors the extensions in rendering), and update the Makefiles that reference it.

Maybe even generate a plaintext `README` with stripped markup elements, if needed (not sure on this one) :)

**Comment by aquette** [comment]
This is a longstanding "issue"!
iirc, github honors both .asciidoc and .adoc extensions for AsciiDoc markup. I'll make something beside this PR (that won't be merged, but keeping it open as a reminder for now)
Staging work visible here: https://github.com/aquette/nut/tree/gh_adoc

**Comment by aquette** [comment]
closing in favor of #669

**Pull request closed without merging**
