### PR TITLE
 Disable mge-xml.c::convert_deci() that was needed a decade ago 

### PR DESCRIPTION
**Pull request by jimklimov**
Made a debug level 5 notice for end-users, and bumped subdriver version for clarity.

Note: version bump from 0.26 to 0.28 accounts for another recent PR against this file that bumps it to 0.27.

### CODE REVIEW

**Comment by clepple** [comment]
I am not too familiar with the XML-capable devices to know how common this problem is, but I don't know if people will think to turn the debug log up to 5 to debug this.

What about a one-time log message at `LOG_NOTICE`?

Also, we have the GitHub issue URL set in configure.ac, so you could add that to the log message with the `PACKAGE_BUGREPORT` macro.

**Comment by jimklimov** [comment]
Thanks for the suggestion, trying it out now....

**Comment by jimklimov** [comment]
As a final round at this "one-line deprecation grown too big", I've made a friendly gesture towards legacy users by offering a configuration toggle to enable the decimation conversion routine, and tested that it works like advertised :)

**Comment by aquette** [comment]
@jimklimov : seconding @zykh in the 2 last comments:
* do_convert-deci should use a VAR_FLAG, which exists for such cases (presence of the flag mean true/on ; absence implies false/off)
* there was a wrong rebase on FTY branch which pulls all the DMF code and more. please revert.

**Comment by jimklimov** [comment]
Yuikes, seems the github web interface fracked something up :\ ETOOMANYREPOS

Regarding VAR_FLAG : do I understand correctly that it has different semantics from the toggle I've added? Meaning, present in config/CLI with (or without) any value means TRUE?

**Comment by jimklimov** [comment]
Force-flushed back the branch to my latest state from yesterday.

**Comment by jimklimov** [comment]
Implemented the suggestion from @zykh so now `do_convert_deci` is a flag and tested that presence or lack of any value does not matter: present == set. And that it still works, e.g.:

````
$ sudo ./drivers/netxml-ups -a 93pm0 -u root -DDDDD -x do_convert_deci=off 2>&1 | ggrep -B5 -A5 -i 'deci'
...
   0.000000	[D5] send_to_all: SETINFO driver.parameter.do_convert_deci "off"
...
   0.719646	[D3] mge_xml_startelm_cb: name <OBJECT> (parent = 300, state = 301)
   0.719689	[D3] mge_xml_cdata_cb: cdata [8] (state = 301)
   0.719725	[D3] mge_xml_endelm_cb: name </OBJECT> (state = 301)
   0.719767	[D3] -> XML variable UPS.PowerConverter.Input[1].Phase[1].Current [8] maps to NUT variable input.L1.current
   0.719812	convert_deci() is now deprecated, so values from XML are normally not decimated. This driver instance has however configured do_convert_deci in your ups.conf, so this behavior for old MGE NetXML-capable devices is preserved.
   0.719913	[D4] -> XML variable UPS.PowerConverter.Input[1].Phase[1].Current [8] which maps to NUT variable input.L1.current was converted to value 0.8 for the NUT driver state
   0.719949	[D5] send_to_all: SETINFO input.L1.current "0.8"
````

````
$ sudo ./drivers/netxml-ups -a 93pm0 -u root -DDDDD  2>&1 | ggrep -B5 -A5 -i 'deci'
...
   0.735048	[D3] mge_xml_cdata_cb: cdata [8] (state = 301)
   0.735086	[D3] mge_xml_endelm_cb: name </OBJECT> (state = 301)
   0.735129	[D3] -> XML variable UPS.PowerConverter.Input[1].Phase[1].Current [8] maps to NUT variable input.L1.current
   0.735178	convert_deci() is now deprecated, so values from XML are not decimated. If you happen to have an old MGE NetXML-capable device that now shows measurements 10x too big, and a firmware update does not solve this, please inform NUT devs via the issue tracker at https://github.com/networkupstools/nut/issues with details about your hardware and firmware versions. Also try to enable do_convert_deci in your ups.conf
   0.735220	[D5] convert_deci() is now deprecated, so value '8' is not decimated. If this change broke your setup, please see details logged above.
   0.735253	[D4] -> XML variable UPS.PowerConverter.Input[1].Phase[1].Current [8] which maps to NUT variable input.L1.current was converted to value 8 for the NUT driver state
   0.735288	[D5] send_to_all: SETINFO input.L1.current "8"
````

**Comment by zykh** [comment]
(if this PR gets merged before #390, we have to remember to adjust subdriver version number)

**Comment by jimklimov** [comment]
Of course, I'd take care of that. Also, github will complain about a merge conflct ;)

**Pull request merged**
