### PR TITLE
Document configure options regarding Python (module, app)

### PR DESCRIPTION
**Pull request by jimklimov**
Closes: #1787

### CODE REVIEW

**Comment by gdt** [comment]
In general this feels too complicated. 
  * If python is used as a build tool that should be separate from the target.
  * It seems nut should find and select a single python (to be used after nut is installed)
  * The default should steer to python3.N first, and bare python3 (which by definition is a pointer that might get changed)
  * There is code that works with 3 as the standard approach.  If there's py27 code, fine, install that when 2 is selected.  If that's done optionally *also*, make that opt in.   I can't imagine anyone wanting that unless their system is python3-deficient.
  * I see zero need for dispatching at runtime.   That just seems like extra complexity that solves a problem people shouldn't have.

**Comment by gdt** [comment]
You mentioned `realpath` and I am not sure you meant that literally.
POSIX specifies `realpth(3)` but there is no requirement for a `realpath(1)` and NetBSD (and likely others) does not have one.

A thought is that given a `--with-python=FOO`, one can just run `FOO-config --prefix`` to find the prefix, avoiding a lot of complexity.

**Comment by jimklimov** [comment]
Well, for systems that have it - literally indeed. For others, fall back to the "FOO" pathname (which may be a symlink so less useful).

Good point about `FOO-config`, quite worth trying it as a fallback too. Not ubiquitous though, fewer and fewer projects and/or packages ship a `FOO-config` script/program.

**Comment by gdt** [comment]
I thought that e.g. python3.10-config was the standard approach in python's install -- that's not the kind of thing pkgsrc makes up.   But fair point that if others don't follow that, you can't relay on it.

But, I only really care what happens when one provides the full path to a real program, since that's how my world is.

**Comment by gdt** [comment]
Thanks for working on this.  I tested this and it's mostly ok.  However, with `--with-python=/usr/pkg/bin/python3.10` I still ended up with files installed to python2.7.   I'm rebuilding with `--without-python2` which is easy enough, but I don't think that should be necessary after specifying a python version.

**Comment by jimklimov** [comment]
As a counter-offer, I'll update the docs with the suggestion to use the option :)

**Comment by jimklimov** [comment]
Heh, `pythonX-config` is (always?..) a python script itself, so has a useful shebang...

**Comment by jimklimov** [comment]
Neat:
````
:; ./autogen.sh && ./configure --without-all --with-pynut
...
checking for python... python
configure: WARNING: A python program name without a specific version number was requested (may be a symlink prone to change over time): /usr/bin/python
checking python interpeter to call... /usr/bin/python (sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0))
checking python site-packages location... /usr/local/lib/python3.8/dist-packages
checking for python2... python2
checking python2 interpeter to call... /usr/bin/python2 (sys.version_info(major=2, minor=7, micro=18, releaselevel='final', serial=0))
checking python2 site-packages location... /usr/local/lib/python2.7/dist-packages
configure: WARNING: A python3 program name was not specified during configuration, will default to '/usr/bin/python3.8' (derived from --with-python setting which has a suitable version)
checking python3 interpeter to call... /usr/bin/python3.8 (sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0))
checking python3 site-packages location... /usr/local/lib/python3.8/dist-packages
...
````

So here the `python` value as defaulted was used almost as such -- just resolved to `/usr/bin/python` (with warnings about the uncertainty). Similarly for `python2`.

However for `python3` defaulted to try the value of `PYTHON` first because it has `major=3`, the complete `/usr/bin/python3.8` path got discovered.

Wondering how well MSYS2/mingw would play with that, considering its resolution to windows paths rather than POSIXy shims:
````
$ which python ; python -c 'import sys; print(sys.executable);'
/mingw64/bin/python
C:/msys64/mingw64/bin/python.exe
````

And ouch, this does not help build confidence (gotta filter discovered names after all):
````
$ cat /mingw64/bin/python-config
#!/bin/sh
````

**Comment by jimklimov** [comment]
Hm, seems --without-python2 now misbehaves

**Comment by gdt** [comment]
Let me know when you want me to retest (i.e., when you have come to a stopping place and think it's ok).

**Comment by jimklimov** [comment]
> Let me know when you want me to retest (i.e., when you have come to a stopping place and think it's ok).

Hopefully found the responsible typo, fixed.

````
:; rm -f Makefile configure ; ./autogen.sh && ./configure --without-all --with-pynut --without-python2
...
checking for python... python
configure: WARNING: A python program name without a specific version number was requested (may be a symlink prone to change over time): /usr/bin/python
checking python interpeter to call... /usr/bin/python (sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0))
checking python site-packages location... /usr/local/lib/python3.8/dist-packages

checking python2 interpeter to call... no

configure: WARNING: A python3 program name was not specified during configuration, will default to '/usr/bin/python3.8' (derived from --with-python setting which has a suitable version)
checking python3 interpeter to call... /usr/bin/python3.8 (sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0))
checking python3 site-packages location... /usr/local/lib/python3.8/dist-packages

...

* install NUT-Monitor desktop application:      no
* install PyNUT binding module: yes
* Default  Python  interpreter  :       /usr/bin/python
* Default  Python  site-packages:       /usr/local/lib/python3.8/dist-packages
* Specific Python2 interpreter  :
* Specific Python2 site-packages:
* Specific Python3 interpreter  :       /usr/bin/python3.8
* Specific Python3 site-packages:       /usr/local/lib/python3.8/dist-packages
````

**Comment by gdt** [comment]
I made a distfile from this and am able to build it in pkgsrc with only the chosen python.  So WORKSFORME and thanks for hacking on this.

**Comment by jimklimov** [comment]
Super! Thanks for the report!

**Pull request merged**
